資格情報を記載
saitamau-maximum/public-website pull request #110
Opened 2024-10-08 02:38 UTC by shigekk

2024-10-08 03:19 UTC, a01sa01to commented
フォーマット落ちてるっぽいので直してもらって

2024-10-08 12:28 UTC, sor4chi requested changes
よろしく！質問多くなっちゃった

2024-10-08 12:28 UTC, sor4chi commented on src/app/achievements/page.tsx
> +          <h2>保有資格</h2>
これ消し忘れかな？
タイトル上と被ってるけど何か意図ある？
![image](https://github.com/user-attachments/assets/d03633a3-1964-4cb0-b996-4ed4ffe2a0a7)

2024-10-08 12:28 UTC, sor4chi commented on src/app/achievements/page.tsx
> +          <h3>当サークルの部員が現在保有している資格について記載します。</h3>
文章はpタグで書きましょう、hタグは見出しとして使うタグです！
もしhタグ相当の文字の大きさとか太さが欲しいって場合はcssで変えよう

2024-10-08 12:28 UTC, sor4chi commented on src/app/achievements/page.tsx
> +
2024年9月時点ってかけると尚よさそう

2024-10-08 12:28 UTC, sor4chi commented on src/app/achievements/list-styles.module.scss
> +    width: 85%;
ここ100%でいいきがする、なんか意図ある？

2024-10-08 12:35 UTC, shigekk commented on src/app/achievements/list-styles.module.scss
> +    width: 85%;
![image](https://github.com/user-attachments/assets/cae12633-4774-4630-ad0b-cfd7652c0f48)
![image](https://github.com/user-attachments/assets/e912ec43-8b9d-4801-b5aa-e62da856a57a)
100だと少し大きいかなと思いまして
こだわりはないので100でもいいですが、どうしますか

2024-10-09 11:49 UTC, hana-rs approved these changes

2024-10-10 01:14 UTC, sor4chi requested changes

2024-10-10 01:14 UTC, sor4chi commented on src/app/achievements/list-styles.module.scss
> +    padding: 40px 40px 103px;
ここなんで0 -> 40pxになってるんだっけ
![スクリーンショット 2024-10-10 午前10 11 59](https://github.com/user-attachments/assets/b4f63671-c24a-4e40-ab13-ff2c13741eab)
![スクリーンショット 2024-10-10 午前10 12 11](https://github.com/user-attachments/assets/3d4e5b66-ce98-42d8-aced-6df9a1bae3e2)
https://maximum.vc
ではモバイル時の横余白もっと小さいんだけどデザイン変更あった感じ？

2024-10-10 02:05 UTC, shigekk commented on src/app/achievements/list-styles.module.scss
> +    padding: 40px 40px 103px;
components/AchievementCard/AchievementCard.module.scssのほうで横のmarginをなくした分こっちで余白をつくろうと思ってこうしました

2024-10-10 02:10 UTC, shigekk commented on src/app/achievements/list-styles.module.scss
> +    padding: 40px 40px 103px;
ちょっと広すぎたかも

2024-10-10 02:32 UTC, sor4chi commented on src/app/achievements/list-styles.module.scss
> +    padding: 40px 40px 103px;
0でいいと思うんだけどどうかな

2024-10-10 02:59 UTC, shigekk commented on src/app/achievements/list-styles.module.scss
> +    padding: 40px 40px 103px;
0にすると画面の幅によっては余白が消滅しちゃうので20くらいは残してもいいかなと思ってます

2024-10-10 08:40 UTC, shigekk commented
close #109

2024-10-10 11:01 UTC, sor4chi approved these changes

2024-10-10 23:19 UTC, yukikamome316 approved these changes

2024-10-11 03:27 UTC, merged