Feat/pre-commit hookを入れる
saitamau-maximum/public-website pull request #13
Opened 2024-03-04 10:00 UTC by nakamuraitsuki

よろしくお願いします

2024-03-04 15:00 UTC, a01sa01to commented on package.json
> +      "pre-commit":"prettier --write . && eslint --fix ."
ここは `lint:fix`, `format` のコードを使いまわしたいです (`yarn lint:fix && yarn format` でできるはず)

ところで、これって正しく hook 入れられてますか？
このファイルを見た感じだと正しくフォーマットできていないように見えます

2024-03-04 15:00 UTC, a01sa01to commented on %1
このファイルは消してください :pray:

2024-03-05 08:03 UTC, nakamuraitsuki commented on package.json
> +      "pre-commit":"prettier --write . && eslint --fix ."
できていませんでした。
古いバージョンのやり方をやってしまっていました。すみません。

2024-03-05 09:09 UTC, a01sa01to requested changes
`.husky/_/.gitignore` があるのに ignore されてないですね :thinking:

`.husky/_` 配下を変更するのではなく、 `.husky/pre-commit` を作成して、そこにコマンドを書いてみてください！
ref: <https://typicode.github.io/husky/how-to.html> の Adding a New Hook

また、 `.husky/_` を Tracking から外す必要があるので、 `git rm --cached .husky/_` を実行してください :bow:

2024-03-05 09:10 UTC, a01sa01to commented on package.json
> +      "pre-commit":"prettier --write . && eslint --fix ."
あるあるなので気にせず！

2024-03-05 09:52 UTC, a01sa01to requested changes
ここだけ直していただければ！

2024-03-05 09:52 UTC, a01sa01to commented on package.json
> +    "prepare": "husky install"
現在 `husky install` ではなく `husky` のみで大丈夫らしいです

2024-03-05 10:06 UTC, a01sa01to approved these changes
問題なしです！お疲れ様でした！！

2024-03-05 10:08 UTC, a01sa01to commented
@yukikamome316 問題なさそうなら Approve してくれ
Commit 多いので Squash Merge するとよさそう

2024-03-05 10:18 UTC, yukikamome316 requested changes
READMEに `yarn prepare` に関する記載を載せてほしい！

2024-03-05 10:18 UTC, yukikamome316 commented on package.json
>      "lint:fix": "npm run lint --fix",
申し訳ないけど
`yarn lint --fix`
に直してもらえると助かる！

2024-03-06 08:02 UTC, yukikamome316 requested changes

2024-03-06 08:02 UTC, yukikamome316 commented on package.json
>      "lint:fix": "npm run lint --fix",
`lint:fix` のコマンドでnpmを使うようになっちゃってるんだけど、これを `yarn lint --fix` に修正してほしい！

2024-03-06 10:42 UTC, yukikamome316 approved these changes
いいね！お疲れ様～

2024-03-06 10:43 UTC, merged