feat/aboutページの編集
saitamau-maximum/public-website pull request #14
Opened 2024-03-04 12:28 UTC by nakamuraitsuki

現在のmaximum.vcに書いてあるようなことを書きました。画像などは入れていない状態です。
実績の詳細ページができていないと思うので、その部分はachievementにリンクしておきました。
よろしくお願いします。

2024-03-04 12:53 UTC, batora9 commented
@a01sa01to @sor4chi 雑なissue作ってすみません。デザインは後にして画像を挿入するところまでやったほうがいいですか？それとも先にマージしちゃった方がいいですか？

2024-03-04 14:55 UTC, a01sa01to commented
画像があるのであれば、デザイン後にして画像を挿入しちゃったほうがいいと思います
そのほうがデザインする側も考えやすいと思うので

2024-03-04 17:40 UTC, batora9 requested changes
画像入れた方がよさそう

2024-03-04 18:01 UTC, sor4chi requested changes
じゃあ自分からは技術的な指摘を🙇‍♂️

すごいマニアックなWebの話なのでへーって思ってくれればOK!

2024-03-04 18:01 UTC, sor4chi commented on src/app/about/page.tsx
> +      </div>
（参考程度に）ただし例外としてブログカードなどデザイン都合でリンクをブロックとして扱うような場合もあり、そのような場合はaタグにcssで`display:block`をつけることでaをブロック要素として扱い、その中をspan等で構成することもできます。

2024-03-04 18:01 UTC, sor4chi commented on src/app/about/page.tsx
> +      </div>
ここも同じです！

2024-03-05 03:13 UTC, sor4chi commented on src/app/about/page.tsx
> +        <a href='../achievements'>
あとprefetchだけじゃなくてSPA遷移ができます（補足）

2024-03-05 03:14 UTC, sor4chi commented on src/app/about/page.tsx
> +          <strong>過去の成績|Maximum</strong>
そうだけどいくらでも調整できるしたまたまインラインの勉強の題材になったしそのままでもいいかな

2024-03-05 03:15 UTC, sor4chi requested changes

2024-03-05 03:15 UTC, sor4chi commented on src/app/about/page.tsx
> +        <a href='../achievements'>
そういえばリンクは基本`/`からの絶対パスの方がいいと思います！
（このページのパスをコピペで動かした時に動かなくなるなどして変更に強くないので！）

2024-03-05 03:15 UTC, sor4chi commented on src/app/about/page.tsx
> +        <a href='../achievements'>
下も同じくです！

2024-03-05 09:39 UTC, yukikamome316 commented on src/app/about/page.tsx
> +        <a href='../achievements'>
Aboutページの編集はなるべく避けたいので、自分はこのままで行きたいと思ってます

2024-03-05 19:36 UTC, sor4chi approved these changes
お疲れ様！

2024-03-06 07:57 UTC, yukikamome316 requested changes

2024-03-06 07:57 UTC, yukikamome316 commented on src/app/about/page.tsx
> +      <img src='/images/ics-pamphlet.png' alt='情報工学科パンフレット' />
`img` タグを使うよりも、Next.js の `Image` コンポーネントを使うと最適化されていいかもしれない！
https://qiita.com/pikimaru/items/7b7aae8a927168351d28

2024-03-06 11:21 UTC, nakamuraitsuki commented on src/app/about/page.tsx
> +      <img src='/images/ics-pamphlet.png' alt='情報工学科パンフレット' />
![スクリーンショット 2024-03-06 201850](https://github.com/saitamau-maximum/public-website/assets/132897891/35c4481f-84e1-422b-b551-76f7672a389e)
[https://nextjs.org/docs/messages/export-image-api](url)
何か変更があったようで、今の状態だとうまく使えなそうなのですが、どうしたらよいですか。

2024-03-06 11:36 UTC, yukikamome316 approved these changes
good!

2024-03-06 11:44 UTC, nakamuraitsuki commented on src/app/about/page.tsx
> +      <img src='/images/ics-pamphlet.png' alt='情報工学科パンフレット' />
承知しました

2024-03-06 11:48 UTC, batora9 approved these changes

2024-03-06 11:54 UTC, merged

2024-03-06 20:02 UTC, sor4chi commented on src/app/about/page.tsx
> +      <img src='/images/ics-pamphlet.png' alt='情報工学科パンフレット' />
なのでSSGで画像最適化かけたい場合はimage loaderを外部に用意するか、自分でビルド時に最適化をかけるスクリプトを作る必要があります