Feat/achievementページの一覧表示
saitamau-maximum/public-website pull request #18
Opened 2024-03-06 14:01 UTC by batora9

2024-03-06 14:12 UTC, a01sa01to commented on src/app/achievements/page.tsx
> +  const fileNames = fs.readdirSync(dir);
どうせ async にしてるなら readdir も `fs/promises` から import すれば `await` できるよとだけ (readFile も同様)

2024-03-06 14:12 UTC, a01sa01to requested changes

2024-03-06 14:12 UTC, a01sa01to commented on src/app/achievements/page.tsx
> +          <a href={`/achievements/${doc.slug}`}>{doc.frontmatter.title}</a>
next/link にしよう

2024-03-06 14:23 UTC, yukikamome316 requested changes

2024-03-06 14:23 UTC, yukikamome316 commented on src/app/achievements/page.tsx
> +  docs.sort((a, b) => (a.frontmatter.date < b.frontmatter.date ? 1 : -1));
`updated_at` の項目を作って、最近の活動を強調した方がいいかも？

2024-03-06 14:31 UTC, yukikamome316 requested changes

2024-03-06 14:31 UTC, yukikamome316 commented on docs/achievement/wsh.md
> +title: "wsh"
ここのタイトルがそのまま表示されるだろうから、「Web Speed Hackathon」って明記したい

2024-03-06 14:31 UTC, yukikamome316 commented on docs/achievement/ute-1.md
> +title: "ute-1"
これも以下と同様
https://github.com/saitamau-maximum/public-website/pull/18#discussion_r1514582713

2024-03-06 14:31 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +title: "icpc"
これも以下と同様
https://github.com/saitamau-maximum/public-website/pull/18#discussion_r1514582713

2024-03-06 14:31 UTC, yukikamome316 commented on docs/achievement/isucon.md
> +title: "isucon"
これも以下と同様
https://github.com/saitamau-maximum/public-website/pull/18#discussion_r1514582713

2024-03-06 14:31 UTC, yukikamome316 requested changes
これもお願い！

2024-03-06 14:50 UTC, yukikamome316 approved these changes

2024-03-06 14:51 UTC, yukikamome316 approved these changes
OK!

2024-03-07 04:18 UTC, sor4chi requested changes
レビュー遅くなってしまって申し訳ない、お願いします！

2024-03-07 04:18 UTC, sor4chi commented on src/app/achievements/page.tsx
> +  const fileNames = fs.readdirSync(dir);
せっかくなのでsync fsじゃなくてpromise fsからreddirを呼ぼう

2024-03-07 04:18 UTC, sor4chi commented on src/app/achievements/page.tsx
> +      const fileContents = fs.readFileSync(filePath, "utf8");
ここもせっかくなのでsync fsじゃなくてpromise fsからreddirを呼ぼう

2024-03-07 04:18 UTC, sor4chi commented on src/app/achievements/page.tsx
> +const getMarkdown = async (dir: string) => {
複数のマークダウンオブジェクトが返ってくる関数なので命名を複数形にしようか
`getMarkdowns`でどうだろう

2024-03-07 04:18 UTC, sor4chi commented on src/app/achievements/page.tsx
> +const getMarkdown = async (dir: string) => {
この関数、多分他の場所からも今後呼ぶことになると思うので、`src/utils/markdown`とかに切り出しましょうか

2024-03-07 04:18 UTC, sor4chi commented on src/app/achievements/page.tsx
> +  docs.push(...getDocs.map((doc) => ({ ...doc })));
これはこうでいいはず
```suggestion
  docs.push(...getDocs);
```

2024-03-07 04:24 UTC, sor4chi commented on src/app/achievements/page.tsx
> +const getMarkdown = async (dir: string) => {
この時、`interface Doc`も`utils`の方に移動して、getMarkdownの戻り値の方を`Doc[]`にしよう

2024-03-07 05:11 UTC, sor4chi requested changes
あと少し！

2024-03-07 05:11 UTC, sor4chi commented on src/utils/markdown.ts
> +      // ファイル名からカテゴリを取得
細かいけどコメントが違うので変えよう
「取得結果からDocオブジェクトを作成」

2024-03-07 05:11 UTC, sor4chi commented on src/utils/markdown.ts
> +import { promises as fs } from 'fs';
```suggestion
import fs from "fs/promises";
```

2024-03-07 05:11 UTC, sor4chi commented on src/utils/markdown.ts
> +import { promises as fs } from 'fs';
これは非推奨になった古い呼び方なんだよね

2024-03-07 05:12 UTC, batora9 commented on src/utils/markdown.ts
> +import { promises as fs } from 'fs';
なるほどｗｗｗ

2024-03-07 05:12 UTC, sor4chi requested changes

2024-03-07 05:12 UTC, sor4chi commented on src/app/achievements/page.tsx
> +  docs.sort((a, b) => (a.frontmatter.updatedAt < b.frontmatter.updatedAt ? 1 : -1));
```suggestion
  // achievementの中身を取得
  const docsDir = path.join(process.cwd(), "docs", "achievement");
  const docs = await getMarkdowns(docsDir);

  // 一覧を日付でソート
  docs.sort((a, b) => (a.frontmatter.updatedAt < b.frontmatter.updatedAt ? 1 : -1));
```

2024-03-07 05:17 UTC, sor4chi approved these changes
![image](https://github.com/saitamau-maximum/public-website/assets/80559385/f912f345-4554-441e-a648-8420ac284e23)

2024-03-07 05:31 UTC, a01sa01to approved these changes

2024-03-07 05:34 UTC, merged