achievementの内容を移植
saitamau-maximum/public-website pull request #26
Opened 2024-03-07 15:48 UTC by shigekk

誤植が無いかの確認もしていただけるとありがたいです．

2024-03-08 00:35 UTC, yukikamome316 commented
今回はいいけど、ブランチ名に日本語を使うのはやめておこう

2024-03-08 09:38 UTC, yukikamome316 requested changes

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| KKaraage | 2187th |  |  |
```suggestion
| YKKaraage | 187th |  |  |
```
チーム名と順位直そう

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-Trump | 93nd |  |  |
```suggestion
| Maximum-Trump | 93rd |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-VJJ | 142th |  |  |
```suggestion
| Maximum-VJJ | 142nd |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-Variant | 40nd | つくば大会 24th (31th) |  |
```suggestion
| Maximum-Variant | 40nd | つくば大会 24th (31st) |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-UniSchoolFleet | 88nd |  |  |
```suggestion
| Maximum-UniSchoolFleet | 88th |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-bug | 152th |  |  |
```suggestion
| Maximum-bug | 152nd |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| MaximumInpactStraight | 58st	 |  |  |
```suggestion
| Maximum\_Shift\_Key | 49th | 東京大会 28th (33rd) |  |
| Maximum\_Inpact\_Straight | 58th	 |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum_Tsubugumi | 102th |  |  |
```suggestion
| Maximum_Tsubugumi | 102nd |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum-beginner | onorable Mention |  |  |
```suggestion
| Maximum-minimum | Honorable Mention |  |  |
| Maximum-beginner | Honorable Mention |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Maximum_Tomato | 20th	 | 東京大会 Honorable Mention<br>北京大会 26th (36th) |  |
```suggestion
| Keep Time Worker | 20th	 | 東京大会 Honorable Mention<br>北京大会 26th (36th) |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| Wearein_rock	 | Honorable Mention	 |  |  |
```suggestion
| We\_are\_in\_rock	 | Honorable Mention	 |  |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +| OutOfOrder | 21st	 | 函館大会 13th (17th) |  |
```suggestion
| Out\_Of\_Order | 21st	 | 函館大会 13th (17th) |  |
```

2024-03-08 09:38 UTC, yukikamome316 commented on docs/achievement/ute-1.md
https://www.maximum.vc/past-results/ute-1
テーブルを載せてほしい

2024-03-08 20:35 UTC, sor4chi commented
順位のndとstとかの表記揺れすごいんだけどとどうやって統一する？

2024-03-09 00:36 UTC, sor4chi commented
一回マージして、別PRで表記揺れを直してもらうことにしましょう
@yukikamome316 @a01sa01to

2024-03-09 00:39 UTC, sor4chi commented
## yarn.lockのコンフリクト解消方法

1. git pull origin (PR先のブランチ名)
コンフリクトを解消するために、まずはリモートリポジトリの最新のコードをローカルに持ってくる。
2. rm yarn.lock
コンフリクトを解消するために、yarn.lockを削除する。
3. yarn install
yarn.lockを削除したので、yarn installでyarn.lockを再生成する。
4. git add yarn.lock
yarn.lockを再生成したので、git addする。
5. git commit -m "てきとうなメッセージ"
コンフリクトを解消したので、コミットする。

2024-03-09 01:06 UTC, shigekk commented
表記揺れは英語から日本語の「位」に統一しようと思いますが，それで大丈夫ですか

2024-03-09 01:39 UTC, a01sa01to requested changes

2024-03-09 01:39 UTC, a01sa01to commented on docs/achievement/icpc.md
> +| We*are*in_rock	 | Honorable Mention	 |  |  |
直せてなさそう

2024-03-09 01:39 UTC, a01sa01to commented on docs/achievement/icpc.md
> +| Out*Of*Order | 21st	 | 函館大会 13th (17th) |  |
2

2024-03-09 01:45 UTC, sor4chi commented
コンフリクト解消できてなさそう（今までの間に更新入ったのかも）、もう一回やってみて

2024-03-09 03:10 UTC, a01sa01to requested changes

2024-03-09 03:10 UTC, a01sa01to commented on docs/achievement/icpc.md
> +| Maximum*Inpact*Straight | 58st	 |  |  |
```suggestion
| Maximum\_Shift\_Key | 49th | 東京大会 28th (33rd) |  |
| Maximum\_Inpact\_Straight | 58st |  |  |
```

2024-03-09 03:15 UTC, a01sa01to requested changes

2024-03-09 03:15 UTC, a01sa01to commented on docs/achievement/icpc.md
タブ文字が含まれていそうなので空白にする

2024-03-09 11:57 UTC, sor4chi commented
コンフリクトはokそう

2024-03-09 14:24 UTC, yukikamome316 requested changes

2024-03-09 14:24 UTC, yukikamome316 commented on docs/achievement/isucon.md
> +| Maximum.mum | 7,159 | 340位 | 非公表 |
```suggestion
| Maxif. | 58,631 | 25 位 | 5 位 |
| maximum.baby | 15,389 | 142 位 | 非公表 |
| Maximum.mum | 7,159 | 340 位 | 非公表 |
```
ここも統一してスペース入れたい

2024-03-09 14:46 UTC, sor4chi commented on docs/achievement/isucon.md
> +| Maximum.mum | 7,159 | 340位 | 非公表 |
これはformatterでどうにかする話題だと思うんだ
@a01sa01to どう思う

2024-03-10 07:22 UTC, yukikamome316 requested changes

2024-03-10 07:22 UTC, yukikamome316 commented on docs/achievement/icpc.md
> +# ICPC 国際大学対抗プログラミングコンテスト
Webページの冒頭にtitleが表示されるような実装をばとらがしてるから、ここは消してもらった方がいいかも
他のmdも同様にお願い！
![image](https://github.com/saitamau-maximum/public-website/assets/32415464/baf0c500-2274-4e55-98b2-32e742bade6e)

2024-03-10 07:22 UTC, yukikamome316 commented on docs/achievement/icpc.md
俺がまだCI構築してないせいでもあるんだけど、`yarn format` を手動で実行してほしい！

2024-03-10 07:29 UTC, a01sa01to commented on docs/achievement/isucon.md
> +| Maximum.mum | 7,159 | 340位 | 非公表 |
> これはformatterでどうにかする話題だと思うんだ

それはそう

2024-03-10 07:30 UTC, a01sa01to commented on docs/achievement/isucon.md
> +| Maximum.mum | 7,159 | 340位 | 非公表 |
手っ取り早いのは prettier で md もやっちゃうことかな (どうフォーマットされるかわからないけど、たぶんいい感じにやってくれるはず)

2024-03-10 22:56 UTC, sor4chi commented
コンフリクト解消してもろて！@shigekk 
npmに変わったから
https://github.com/saitamau-maximum/public-website/pull/26#issuecomment-1986604305
の3番は`npm i`になります

2024-03-11 04:20 UTC, sor4chi approved these changes

2024-03-11 05:37 UTC, a01sa01to requested changes

2024-03-11 05:37 UTC, a01sa01to commented on docs/achievement/icpc.md
> +| Maximum_TGM | 20 位 | 東京大会 (21st)<br>シンガポール大会 10 位h |  |
```suggestion
| Maximum_TGM | 20 位 | 東京大会 (21st)<br>シンガポール大会 10 位 |  |
```

2024-03-11 14:25 UTC, a01sa01to requested changes

2024-03-11 14:25 UTC, a01sa01to commented on docs/achievement/icpc.md
@shigekk まだありそう、 `\t` を正規表現検索して空白で置き換えてみて
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/9649af84-6917-452b-affe-944c7d6630af)

2024-03-11 15:55 UTC, a01sa01to approved these changes

2024-03-11 17:27 UTC, yukikamome316 approved these changes

2024-03-11 17:27 UTC, merged