feat: Storybookの導入
saitamau-maximum/public-website pull request #29
Opened 2024-03-08 10:51 UTC by yukikamome316

## 概要
とりあえず導入のコマンドを打っただけです

2024-03-08 13:46 UTC, a01sa01to reviewed
ん、どういう意図で public-website 側に Storybook 入れるの？ (単純に話聞いてなかっただけかも)

2024-03-08 14:13 UTC, yukikamome316 commented
> ん、どういう意図で public-website 側に Storybook 入れるの？ (単純に話聞いてなかっただけかも)

デザイン案が完全に仕上がってからCSSを書き始めると納期に間に合わない恐れがあります。そのため、コンポーネント単位でCSSを書き進めていくという方針をとりました。そこで、sor4chiさんによるとStorybookを導入すると楽に書けるとのことで、導入するに至りました。

2024-03-08 20:36 UTC, sor4chi commented
ページできるまでCSS開発待つくらいならコンポーネント単位で始めちゃおう案です

2024-03-08 20:37 UTC, sor4chi requested changes

2024-03-08 20:37 UTC, sor4chi commented on src/stories/Button.stories.ts
デフォルトで生成されるstoriesは消しちゃっていいかも

2024-03-09 14:02 UTC, sor4chi commented
レビュー対応してなくない？

2024-03-09 14:04 UTC, yukikamome316 commented
> レビュー対応してなくない？ @yukikamome316

`src/stories` を全て消すってことですか？

2024-03-09 14:08 UTC, sor4chi commented
そうだね

2024-03-09 14:19 UTC, sor4chi approved these changes

2024-03-10 07:25 UTC, a01sa01to approved these changes

2024-03-10 07:25 UTC, merged