Feat/markdownをhtmlに変換して表示する
saitamau-maximum/public-website pull request #30
Opened 2024-03-10 04:21 UTC by batora9

2024-03-10 07:39 UTC, yukikamome316 approved these changes

2024-03-10 07:42 UTC, yukikamome316 requested changes
間違えてApproveした
npmに置き換えるまで保留

2024-03-10 12:42 UTC, a01sa01to reviewed
大枠としては OK、細かいところだけど一応

2024-03-10 12:42 UTC, a01sa01to commented on src/app/achievements/[slug]/page.tsx
> +      <div dangerouslySetInnerHTML={{ __html: html.content }} />
細かいけど `<article>` を使うと良いです

ref: https://developer.mozilla.org/ja/docs/Web/HTML/Element/article

2024-03-10 12:42 UTC, a01sa01to commented on src/app/achievements/[slug]/page.tsx
> +      <div dangerouslySetInnerHTML={{ __html: html.content }} />
一応 `dangerouslySetInnerHTML` はその名の通り危険なので、なぜこれを使わないといけないかというコメントを書いておくと良いです
細かいことは長くなるので気になったら調べる or 聞いてください

ref: https://github.com/saitamau-maximum/website/blob/cb87c5624a6ee7ef08ad33d8e4472da0790b7269/app/components/ui/breadcrumb.tsx#L64

2024-03-10 12:42 UTC, a01sa01to commented on src/app/achievements/[slug]/page.tsx
> +  return params;
[not change request]
一応こんな感じで書けるよというだけ (知っておいて損はないと思うので)

```suggestion
  return docs.map(doc => ({ slug: doc.replace(/\.md$/, '') }));
```

2024-03-10 18:58 UTC, batora9 commented on src/app/achievements/[slug]/page.tsx
> +  return params;
ありがとうございます

2024-03-10 22:59 UTC, sor4chi requested changes

2024-03-10 22:59 UTC, sor4chi commented on .npmrc.pages
> +always-auth=true
always auth消していいと思う

2024-03-10 22:59 UTC, sor4chi commented on src/app/achievements/[slug]/page.tsx
> +    </article>
articleタグの中にarticleタグをネストするのはよくないはず
外側mainで囲ったらどうかな？

2024-03-10 22:59 UTC, sor4chi commented on src/app/achievements/[slug]/page.tsx
> +export default async function AchievementsSlug( { params } : Props ) {
関数名の命名変えよう
`achievements/[slug]`だから`AchievementsDetail`とかでどうかな？
命名が動作に影響するわけではないんだけどね

2024-03-11 00:10 UTC, sor4chi approved these changes
おけー

2024-03-11 00:23 UTC, merged