feat: newsフォルダ内のmdファイルを取得しhtmlに変換
saitamau-maximum/public-website pull request #36
Opened 2024-03-11 00:37 UTC by batora9

2024-03-11 00:40 UTC, sor4chi requested changes

2024-03-11 00:40 UTC, sor4chi commented on src/app/news/[slug]/page.tsx
> +export async function generateMetadata({ params }: Props): Promise<ResolvingMetadata> {
確か自分で型つけなくてもnextjs側で型が提供されてたはず
`ResolvingMeta`じゃなくてこれを使おう
https://nextjs.org/docs/app/building-your-application/optimizing/metadata#dynamic-metadata
そして指摘し忘れてたけどachivementの方でも同じくなってたら直してほしい

2024-03-11 10:08 UTC, sor4chi approved these changes

2024-03-11 10:09 UTC, batora9 commented on src/app/achievements/[slug]/page.tsx
> +  const filePath = path.join(process.cwd(), `docs`, `achievement`, `${slug}.md`);
!?

2024-03-11 17:26 UTC, yukikamome316 approved these changes

2024-03-11 23:14 UTC, sor4chi commented
なんでachievementフォルダに変えたの？

2024-03-11 23:19 UTC, batora9 commented
これ`achievements/[slug]/page.tsx`がコンフリクト起こしてて`news/[slug]/page.tsx`からコピーしたものを張り付けてしまい、`news`のままになってしまたためです

2024-03-12 00:55 UTC, sor4chi commented
そういうことか！

2024-03-12 01:43 UTC, sor4chi approved these changes

2024-03-12 01:43 UTC, merged