feat: ヘッダー作成
saitamau-maximum/public-website pull request #39
Opened 2024-03-12 04:53 UTC by batora9

モバイル版には対応していません。Figmaのcomponentsにあったものの通りに作りました。

以下、デザイン案になかったので自分で付け加えました
- Maximumロゴはデザイン案にあった色ではなくもともとのブランド色を使う
- リンクをホバーした時の色を`#7FCC8F`にする
- リンクをホバーした時の下線を削除する

2024-03-12 06:04 UTC, a01sa01to requested changes

2024-03-12 06:04 UTC, a01sa01to commented on src/components/Header/Header.tsx
> +        </a>
` a in a` はよくないですね、やるなら `span in a` とか
+
`next/link` を使おう

2024-03-12 06:04 UTC, a01sa01to commented on src/components/Header/Header.tsx
> +import xlogo from '../../../public/logos/x-logo-white.svg';
ロゴの svg データ、 react-icons とかから引っ張ってくるのが良いんだろうか (RFC)

2024-03-12 06:04 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +}
これ CSS Modules だとよくないきがする

2024-03-12 06:06 UTC, batora9 commented on src/components/Header/Header.tsx
> +        </a>
見落としてました...

2024-03-12 06:07 UTC, batora9 commented on src/components/Header/Header.module.css
> +}
@sor4chi これって`body`と`root`は消しちゃっていい感じですか？

2024-03-12 06:09 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +}
固定値なら Sass 変数を使うのもありかも

2024-03-12 09:03 UTC, batora9 commented on src/components/Header/Header.module.css
> +}
@a01sa01to どう修正すればいいかわからないです

2024-03-12 09:21 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +}
これ消したら動かないかんじ？

2024-03-12 09:38 UTC, sor4chi commented on src/components/Header/Header.module.css
> +}
まずbodyはglobal styleなのでglobal.cssに書くべきでHeader.module.cssにはいらなくて

2024-03-12 09:38 UTC, sor4chi commented on src/components/Header/Header.module.css
> +}
css変数はこれで良くないか？

2024-03-12 09:42 UTC, batora9 commented on src/components/Header/Header.module.css
> +}
`root`消すと正しく動かないです

2024-03-12 09:46 UTC, sor4chi requested changes

2024-03-12 09:46 UTC, sor4chi commented on src/components/Header/Header.module.css
> +}
これはいらない！ロゴの<img>にw/hが設定されてるから高さと幅はそっちで確保してくれます！

2024-03-12 09:46 UTC, sor4chi commented on src/components/Header/Header.tsx
> +        <Link href='/about'>
`Link`の中にpはあんまりみないのでやめよう
pはparagraph(文章)のpだから文章まるまるリンクで囲うみたいなことしてる感じになってる
基本link内で文字列をタグ分割するときはspanを使うんだけど、今回の場合はLink内で文字列分割することがなさそうなので何も囲わないで

```ts
<Link href="/news">
  News
</Link>
```

みたいな形でいいとおも

2024-03-12 09:46 UTC, sor4chi commented on src/components/Header/Header.module.css
> +}
ん？root消せとは言ってないつもりだった

2024-03-12 09:54 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +}
あ、勢い余って範囲間違えてた、すまん

2024-03-12 10:16 UTC, a01sa01to requested changes

2024-03-12 10:16 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +}
`a` で一括指定するんじゃなくて `Link` のクラスで `style.a` みたいに指定したほうがいい気がする？

2024-03-12 10:16 UTC, a01sa01to commented on src/components/Header/Header.module.css
> +  position: relative;
これ画面スクロールしても header がついてこない気がする

2024-03-12 10:16 UTC, a01sa01to commented on src/components/Header/Header.tsx
> +          <span>Blog↗</span>
↗ は環境依存文字なので使わないほうが良さそう
`<MdArrowOutward />` がそれっぽいので、ロゴと合わせて react-icons 導入しちゃっていいと思ってます
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/a75f4d52-1341-48a9-91ed-0d11991c2a31)

2024-03-12 10:56 UTC, sor4chi commented
基本的にmodule cssなら`*.module.css`にタグセレクタ使うのはアウトです！クラスセレクタ縛りしましょう

2024-03-14 04:06 UTC, a01sa01to requested changes

2024-03-14 04:06 UTC, a01sa01to commented on src/components/Header/Header.tsx
> +import { IoLogoGithub } from "react-icons/io";
Simple Icons (`react-icons/si`) にロゴ系がまとまってるのでそっちを使ったほうがいいかも！

2024-03-14 04:06 UTC, a01sa01to commented on public/logos/github-logo-white.svg
こっちのロゴは消しちゃって OK！

2024-03-14 04:06 UTC, a01sa01to commented on public/logos/x-logo-white.svg
これも

2024-03-14 04:14 UTC, sor4chi requested changes

2024-03-14 04:14 UTC, sor4chi commented on src/components/Header/Header.module.css
> +.navigations a{
子要素のaタグをそのまま指定するくらいなら、`next/link`の`Link`コンポーネントにはclassつけられるので`.navigationLink`みたいなクラス作ってそれを`<Link class="navigationLink" />`で呼びましょう

2024-03-14 04:14 UTC, sor4chi commented on src/components/Header/Header.module.css
> +.navigations a{
html要素に直接スタイル当てるのはあんま良くないので！

2024-03-14 04:14 UTC, sor4chi commented on src/components/Header/Header.tsx
> +        <Link href='https://blog.maximum.vc'>
これ新規タブで開くようにしなくていいのかな？

2024-03-14 04:14 UTC, sor4chi commented on src/components/Header/Header.tsx
> +          <FaXTwitter size={29} />
`24/28/32`のどれかにしたい

2024-03-14 04:16 UTC, batora9 commented on src/components/Header/Header.tsx
> +        <Link href='https://blog.maximum.vc'>
わすれてました
します

2024-03-14 04:17 UTC, batora9 commented on src/components/Header/Header.tsx
> +          <FaXTwitter size={29} />
@hana-rs ロゴのサイズどうしますか

2024-03-14 04:18 UTC, sor4chi requested changes

2024-03-14 04:18 UTC, sor4chi commented on src/components/Header/Header.tsx
> +          <span>About</span>
そもそも`<Link>`の中`<span>`で囲う必要ないかも

2024-03-14 08:02 UTC, yukikamome316 approved these changes

2024-03-14 09:28 UTC, a01sa01to requested changes
Storybook 側の public dir 設定がされてない (Discord で言ったけど記録として)

2024-03-14 10:54 UTC, a01sa01to approved these changes
OK～

2024-03-14 11:42 UTC, sor4chi approved these changes
おけー

2024-03-14 14:06 UTC, merged