ボタンを作る
saitamau-maximum/public-website pull request #46
Opened 2024-03-14 14:09 UTC by shigekk

2024-03-14 15:27 UTC, batora9 requested changes
storybookあるからプレビューできるように`*.stories.tsx`あるといいかも

2024-03-15 00:47 UTC, a01sa01to requested changes

2024-03-15 00:47 UTC, a01sa01to commented on src/app/components/Button.tsx
> +    </Link>
a の中に button はよくないです (tab キーで移動したときに二重にフォーカスされる)

> ボタンですが `<Link>`コンポーネントで作ってください。

はつまり `<button>` を使わずに作ろうってことなので、 `<button>` を使わずに作ってみてください！

2024-03-15 00:47 UTC, a01sa01to commented on src/app/components/Button.tsx
> +    <Link href={href} passHref>
`passHref`、必要？

2024-03-15 00:47 UTC, a01sa01to commented on src/app/components/Button.tsx
> +  const className = `${styles.button} ${variant === 'green' ? styles.greenButton : styles.grayButton}`;
`clsx` っていうライブラリを入れてみるとすっきりするかも...？

2024-03-15 00:47 UTC, a01sa01to commented on src/app/components/Button.module.css
> +  border-radius: 80px
```suggestion
  border-radius: 80px;
```

80px も必要...？

2024-03-15 00:47 UTC, a01sa01to commented on src/app/components/Button.module.css
> +  border-radius: 0px;
0px は想定通りの値？

2024-03-15 01:09 UTC, sor4chi commented on src/app/components/Button.module.css
> +  border-radius: 80px
@a01sa01to  逆に正円を明示するために`999px`でいいと思うんだけど

2024-03-15 01:12 UTC, sor4chi requested changes

2024-03-15 01:12 UTC, sor4chi commented on src/app/components/Button.module.css
> +  font-size: 24px;
`font-size`はブラウザにアクセスした人の文字サイズの設定に依存してほしい（老眼など）ので
`font-size: 1.5rem` -> 通常設定の人だと`24px`にしましょう

2024-03-15 01:12 UTC, sor4chi commented on src/app/components/Button.module.css
> +  border-radius: 0px;
0の時はborder-radiusいらなさそう！

2024-03-15 04:01 UTC, a01sa01to requested changes

2024-03-15 04:01 UTC, a01sa01to commented on src/app/components/Button.tsx
> +      <span className={className} role="button" tabIndex={0}>
span を消してもよさそう？

```suggestion
    <Link href={href} className={className}>
```

- このボタンはページ移動することを前提にしてる (=ボタンじゃなくてリンクとして働く) ので `role="button"` は正しくなさそう
  - やるなら `role="link"` だけど a (= Link) タグにしてるから不要
- tabIndex は a タグにはデフォルトになってるっぽいので不要

2024-03-15 04:31 UTC, shigekk commented on src/app/components/Button.tsx
> +      <span className={className} role="button" tabIndex={0}>
![スクリーンショット 2024-03-15 132914](https://github.com/saitamau-maximum/public-website/assets/132898053/ab0652ab-a001-4a29-b857-c21a7fe4da14)

文字に下線が出るようになったのですが，大丈夫ですか

2024-03-15 05:13 UTC, sor4chi commented on src/app/components/Button.tsx
> +      <span className={className} role="button" tabIndex={0}>
`text-decolation: none`をつけて

2024-03-15 07:44 UTC, a01sa01to commented on src/app/components/Button.tsx
> +export const Button: React.FC<ButtonProps> = ({ href, label, variant }) => {
名前 `LinkButton` とかに変えたほうがいいかも？ (ファイル名も)

2024-03-15 11:20 UTC, sor4chi commented
もしかして`clsx`のライブラリ入ってない...？
`npm i clsx`でライブラリをインストールしましょう！

2024-03-16 02:43 UTC, shigekk commented on src/app/components/Button.stories.tsx
> +  href: '/',
すみません，どうしたらいいのかわからないです．

2024-03-16 03:08 UTC, sor4chi commented
@shigekk ↑

2024-03-16 07:15 UTC, sor4chi commented
コンフリクト解消もできる？前とやり方同じ

2024-03-16 11:05 UTC, shigekk commented
![スクリーンショット 2024-03-16 200423](https://github.com/saitamau-maximum/public-website/assets/132898053/b784cd1c-7638-4198-a84a-0202bef62e3a)

これが解決できません

2024-03-16 11:16 UTC, shigekk commented
だれか助けてください

2024-03-16 11:25 UTC, sor4chi commented
@shigekk 
`npm i`してないんじゃない？

2024-03-16 11:31 UTC, shigekk commented
![スクリーンショット 2024-03-16 202905](https://github.com/saitamau-maximum/public-website/assets/132898053/1655e68f-2c2e-48bc-b216-afae8a39c6ef)

これは出来てますよねたぶん

2024-03-16 11:42 UTC, sor4chi commented
> ![スクリーンショット 2024-03-16 200423](https://private-user-images.githubusercontent.com/132898053/313399955-b784cd1c-7638-4198-a84a-0202bef62e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODk2MTEsIm5iZiI6MTcxMDU4OTMxMSwicGF0aCI6Ii8xMzI4OTgwNTMvMzEzMzk5OTU1LWI3ODRjZDFjLTc2MzgtNDE5OC1hODRhLTAyMDJiZWY2MmUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxMTQxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzFkNjZlN2Q0Yzg2YzA1MWZiZTBkYmZjZjBlM2NiYzIwZmFkZjFmODNhZGY2YjljMmM0MDAwZmQ5MzA5OTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JRdxrQFerLRLCgvHpEgC35DeOei8ayk5KD-5c5A1vzk)
> 
> これが解決できません

直したいのはこれの

2024-03-16 11:54 UTC, shigekk commented
Errorの方です．これのせいでcommitできないのかなと思ってます

2024-03-16 14:14 UTC, sor4chi commented
なんでerror出るんdな

2024-03-16 14:17 UTC, sor4chi requested changes

2024-03-16 14:17 UTC, sor4chi commented on package.json
> +    "react-router-dom": "^6.22.3"
そもそもerrorの原因、`react-icons`のインストール忘れじゃない？
もしインストールされてればここに`react-icons`があるはず

2024-03-16 14:17 UTC, sor4chi commented on src/app/components/Button.tsx
なんで`Button.tsx`と`Button.stories.tsx`あるのかな？消し忘れ？

2024-03-16 14:44 UTC, shigekk commented
![スクリーンショット 2024-03-16 234356](https://github.com/saitamau-maximum/public-website/assets/132898053/4843a69e-98d2-4597-b07c-c1b9e8628f17)
今こうなってます

2024-03-16 15:30 UTC, sor4chi commented
それaddしてコミットしたらpushできない？

2024-03-16 15:56 UTC, shigekk commented
コミットしようとするとこうなります
![Uploading スクリーンショット 2024-03-17 005541.png…]()

2024-03-16 15:57 UTC, shigekk commented
![スクリーンショット 2024-03-17 005541](https://github.com/saitamau-maximum/public-website/assets/132898053/feaf167a-e4eb-4bed-8b4f-0d1ab6e93aa8)

2024-03-16 16:27 UTC, sor4chi commented
うーん、なんでだろ
もし明日解決できてなかったら時間ある時VCしよう

2024-03-16 16:32 UTC, shigekk commented
ほんとに
ありがとうございます

2024-03-17 08:00 UTC, sor4chi approved these changes
お疲れ！

2024-03-17 08:26 UTC, yukikamome316 approved these changes

2024-03-17 08:26 UTC, yukikamome316 commented on src/components/LinkButton/LinkButton.tsx
> +};
```suggestion
interface ButtonProps {
  href: string;
  variant: 'green' | 'gray';
  children: React.ReactNode;
}

export const LinkButton: React.FC<ButtonProps> = ({ href, variant, children }) => {
  const className = clsx(
    styles.button,
    variant === 'green' && styles.greenButton,
    variant === 'gray' && styles.grayButton,
  );
  
  return (
    <Link href={href} className={className}>
      {children}
    </Link>
  );
```



今のままだと
```tsx
<LinkButton href='/foo' variant='green' title='ここをクリック'/>
```

みたいな使い方になってしまうから、

```tsx
<LinkButton href='/foo' variant='green''>
    ここをクリック
</LinkButton>
```

って感じで使えるように修正しよう！

2024-03-17 08:27 UTC, yukikamome316 requested changes
まちがえてApproveしちゃった

2024-03-17 08:41 UTC, yukikamome316 approved these changes

2024-03-17 08:48 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.tsx
> +}
Link のほかの props も許容したい気もする...？
そうでもない？

2024-03-17 16:54 UTC, batora9 requested changes
hoverしたときに色変わるようにした方がいいと思う

2024-03-20 00:42 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.tsx
> +    <Link href={href} {...props} className = {className}>
```suggestion
    <Link {...props} href={href} className={className}>
```

2024-03-20 08:40 UTC, a01sa01to approved these changes

2024-03-20 11:16 UTC, batora9 approved these changes
OK!!

2024-03-20 11:17 UTC, merged