Feat/カードコンポーネント作成
saitamau-maximum/public-website pull request #48
Opened 2024-03-20 11:41 UTC by nakamuraitsuki

拙いコードですがどうかよろしくお願いします。

2024-03-20 13:05 UTC, a01sa01to requested changes

2024-03-20 13:05 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +    <a href={link} className={style.card}>
next/link の Link にする

2024-03-20 13:05 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +  link: string;
`href` とか `to` がよさそう？

2024-03-20 13:05 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +        <img src='/images/maximum-card.png' alt='maximum' />
画像は適宜変えられるようにしたいので、画像の src を指定できるといいと思います！

2024-03-20 13:05 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +      <h2 className={style.title}>{title}</h2>
文書構造的には見出しタグ (h1, h2, ...) は使わないほうがいいかな～
p タグとかにして CSS でフォントサイズとか太さとかあてるようにしよう

2024-03-20 14:39 UTC, sor4chi requested changes
CSSの指摘が多いですが抑えて欲しいことは基本この三点です
- font-sizeにはremを使いましょう、`16px = 1rem`と考えて変換してみてください。
- 大体4 or 8px単位でデザインするようにしてます。もしそれ以外(4/8の倍数以外)のpxを書くことになったらそれはFigmaの間違いである可能性が高いのでデザイン担当者に聞くか意図を汲んで勝手に対応するで大丈夫です。
- Figma通りにサイズを設定してしまうと、伸び縮みなど柔軟でないコンポーネントになってしまうので、具体的すぎる値は極力使わないように`%`や`vh/vw`などで工夫して表現できないか考えてみましょう！

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    font-family:Zen Kaku Gothic Antique;
今回のサイトでは全テキストのフォントが`Yu Gothic`で固定されているのでここだけフォント変える！みたいなのは今回発生しないはずでおそらくFigmaのミスかと思います！消しちゃって大丈夫です。

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    line-height: 5px;
box要素にline-heightつけることはあんまりしないので多分これいらないかと思います！

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    font-size: 15px;
```suggestion
    font-size: 1rem;
```

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    font-size: 15px;
```suggestion
    font-size: 1rem;
```

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    margin-top:7px;
ここも左右で1pxだけずれることは多分想定してないし両方8pxでいいと思う！

2024-03-20 14:39 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    height: 33px;
これもFigma通りにやってくれたと思うんだけど、かなり数値が歪になってしまっているので
160 / 32 にしましょう(16の倍数で)
こちらでFigma直しておきます

2024-03-21 03:11 UTC, sor4chi requested changes

2024-03-21 03:11 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    aspect-ratio: 360 / 211;
ここ、直してもらったところ申し訳ないんだけど、やっぱりアスペクト比綺麗な方がいいと思ったので`1920/1080`(HD)くらいにしますか

2024-03-21 03:11 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    float: right;*/
このコメントアウトは消してしまって大丈夫です！

2024-03-21 03:19 UTC, nakamuraitsuki commented on src/components/Card/Card.module.css
> +    float: right;*/
ここがないと、Figmaのような画像の上にかぶせる表示ができませんでした。戻してしまってもよいですか

2024-03-21 03:42 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    float: right;*/
ん、コメント消すと動かないってこと！？なんでだ

2024-03-21 03:43 UTC, nakamuraitsuki commented on src/components/Card/Card.module.css
> +    float: right;*/
コメントアウトの中身のことです

2024-03-21 03:44 UTC, nakamuraitsuki commented on src/components/Card/Card.module.css
> +    float: right;*/
ややこしくてすみません

2024-03-21 04:10 UTC, sor4chi requested changes

2024-03-21 04:10 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    float: right;*/
```suggestion
    position: absolute;
    right: 0;
    bottom:0;
    float: right;
```

動かないならとりあえずコメントアウト戻してもらうか

2024-03-21 04:11 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    float: right;*/
https://github.com/saitamau-maximum/public-website/pull/48#discussion_r1533224294

2024-03-21 07:15 UTC, a01sa01to requested changes

2024-03-21 07:15 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +        <img className={style.img} src={imageSrc} alt='maximum' />
alt も動的に指定できるといいかも！全画像の代替テキストが `maximum` とも限らないので

2024-03-21 07:15 UTC, a01sa01to commented on src/components/Card/Card.stories.tsx
> +  content: 'AAAAAAAAAAAAAAAAAAAA…',
せっかく `text-overflow: ellipsis;` 指定されてるから、

```suggestion
  content: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
```

とか長い文章入れてみて動作チェックしたほうがいいかも

2024-03-21 08:16 UTC, sor4chi requested changes
あとちょっとお願いします！

2024-03-21 08:16 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    text-overflow: ellipsis;
これ、一行以上は3点リーダーにしてoverflowしないようにするみたいなデザインFigmaにあった？
もし意図してない挙動だったらこの三行消すと治るので消して欲しいです！

2024-03-21 08:16 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    display:block;
cardの下にpaddingを入れようか、24pxくらい

2024-03-21 08:16 UTC, sor4chi commented on src/components/Card/Card.module.css
> +    margin-bottom: 0;
ここmargin-bottomも8pxにしよう

2024-03-21 08:31 UTC, nakamuraitsuki commented on src/components/Card/Card.module.css
> +    text-overflow: ellipsis;
カードの大きさを固定値にしていた時にはみ出すのを防止するためにしてました。
もうなくても大丈夫だと思うので消します

2024-03-21 08:38 UTC, sor4chi approved these changes
![Screenshot 2024-03-21 at 17 38 14](https://github.com/saitamau-maximum/public-website/assets/80559385/3c8c76d7-08f2-4dc6-b56a-67c88fc64c27)
良さそう

2024-03-21 09:49 UTC, a01sa01to approved these changes

2024-03-21 12:15 UTC, merged