feat/aboutページ見た目
saitamau-maximum/public-website pull request #52
Opened 2024-03-22 06:20 UTC by nakamuraitsuki

よろしくお願いします。

2024-03-22 06:47 UTC, a01sa01to requested changes

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +        </p>
もし Card の部分で自分がコメントしたせいだったら申し訳ないんだけど、ここのタイトルは h2 で OK です :bow:
Card の場合は「見出し」ではないので h1 タグとかが大量発生するのはよくないんだけど、このページは段落の見出しなので h1, h2,  ... タグを使ってください！
title は h2、 subtitle は h3 を使おう！

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +        <img className={style.hero} src='/heros/hero-about.png' alt='hero' />
Figma に書いてある通り、 hero はわかめぼかし + タイトル h1 で

![image](https://github.com/saitamau-maximum/public-website/assets/26807394/a7bf06db-32b0-4016-a641-2a721a801a84)

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +        </p>
`<p>` の p は paragraph の p なので、段落に 1 個で OK！
ほかの部分も同様！
改行は `<br />` にするか、端末依存にさせたい

```suggestion
        <p className={style.text}>
          Maximumは、
          <span className={style.highlight}>
            国際大学対抗プログラミングコンテスト（ICPC）
          </span>
          へ参加し、良い成績を上げるために成立したプログラミング研究会です。
          2022年度からは、
          <span className={style.highlight}>競技プログラミング</span>
          のみならず、
          <span className={style.highlight}>Web</span>や
          <span className={style.highlight}>その他プログラミング</span>
          の知識を高める活動を行っています。
        </p>
```

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +        <p className={style.text}>Webアプリを作成・公開してきました。</p>
@yukikamome316 @batora9
ここ内容変えたくない？ @sor4chi いなくなったら内容おかしくならない？

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +      <Header />
@yukikamome316 @batora9 
Header は layout.tsx のほうでまとめちゃったほうがいいんじゃないかな

@nakamuraitsuki 
とりあえず消しちゃって OK だと思います

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/styles.module.css
> +    width: 66%;
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/57f766bc-f728-44fb-a9c5-54c42e4a1b66)

つまり 54rem で！
モバイル対応として max-width: 100% もつけるとよさそう

2024-03-22 06:47 UTC, a01sa01to commented on src/app/about/page.tsx
> +      <div className={style.box}>
メイン部分なので main タグを使おう
https://developer.mozilla.org/ja/docs/Web/HTML/Element/main

2024-03-22 06:51 UTC, a01sa01to commented on src/app/about/page.tsx
> +        <img className={style.hero} src='/heros/hero-about.png' alt='hero' />
ただ時間もないので TODO コメント残していったんそのままでいい気もしますね

```suggestion
        {/* TODO: Hero 画像とタイトルを分離する */}
        <img className={style.hero} src='/heros/hero-about.png' alt='hero' />
```

2024-03-22 07:31 UTC, sor4chi commented on src/app/about/page.tsx
> +        <p className={style.text}>Webアプリを作成・公開してきました。</p>
そんな文章書いたっけw恥ずかしいな
消して欲しいwすいません

2024-03-22 07:36 UTC, sor4chi commented
@ dev
aboutページってmarkdownで内容管理するんじゃないんだっけ

2024-03-22 07:36 UTC, a01sa01to requested changes

2024-03-22 07:36 UTC, a01sa01to commented on src/app/about/page.tsx
> +        {/*スペースを空けるためのもの*/}
これ、 style.text のスタイルに margin-top, bottom を指定していい感じにならない...？

2024-03-22 07:36 UTC, a01sa01to commented on src/app/about/page.tsx
> +        <hr />
hr ではなく css で border-bottom をやったほうがいい気がする？
Figma 見た感じだと h2 に下線が引かれているみたいだし、セクションの区切りじゃないので hr を使いたくないのがあります

2024-03-22 07:36 UTC, a01sa01to commented on src/app/about/page.tsx
> +        </p>
ここもまとめる

2024-03-22 07:36 UTC, a01sa01to commented on src/app/about/page.tsx
> +
ここの空行消しちゃってください！

2024-03-22 07:36 UTC, a01sa01to commented on src/app/about/styles.module.css
> +}
なくても割とよさそう...？

2024-03-24 12:50 UTC, yukikamome316 approved these changes
LGTM!

2024-03-24 15:22 UTC, merged