Footer作成
saitamau-maximum/public-website pull request #54
Opened 2024-03-22 13:55 UTC by shigekk

2024-03-22 14:16 UTC, a01sa01to commented on src/components/Footer/Footer.module.scss
> +  padding: 0px 0px 0px 100px;
```suggestion
  padding-left: 100px;
```

2024-03-22 14:17 UTC, a01sa01to commented on src/components/Footer/Footer.module.scss
> +  padding: 100px 100px 100px 100px;
padding 使わず flex をうまく使えるとよさそう

2024-03-22 14:19 UTC, a01sa01to commented on src/components/Footer/Footer.tsx
> +        </div>
ボタンは Logo じゃないので

```suggestion
        <div className={style.logo}>
          <Link href='/'>
            <img
              src='/logos/Maximum-logo.svg'
              alt='Maximum'
              width={334}
              height={84}
            />
          </Link>
        </div>
        <div className={style.greenButton}>
          <LinkButton href='/join' variant='green'>
            入会案内はこちら
          </LinkButton>
        </div>
```

2024-03-22 14:20 UTC, a01sa01to commented on src/components/Footer/Footer.module.scss
> +  padding: 0px 0px 0px 100px;
これ flex だから padding じゃなくて `.footer` 側の gap を使うとよさそう

2024-03-22 14:46 UTC, shigekk commented
ロゴの色が違うんですが
白いロゴはどこから持ってきたらいいですか

2024-03-22 15:29 UTC, shigekk commented on src/components/Footer/Footer.module.scss
> +  padding: 100px 100px 100px 100px;
ちょっとわからないです

2024-03-23 03:19 UTC, shigekk commented on src/components/Footer/Footer.module.scss
> +  padding: 100px 100px 100px 100px;
![スクリーンショット 2024-03-23 121732](https://github.com/saitamau-maximum/public-website/assets/132898053/c1a27f71-c3b2-406a-964d-95f16fda066f)
paddingかmarginを使わずに余白を作る方法がわからないです

2024-03-23 18:12 UTC, batora9 requested changes

2024-03-23 18:12 UTC, batora9 commented on src/components/Footer/Footer.module.scss
> +  }
```suggestion
.footer {
  display: flex;
  align-items: center;
  background-color: #000;
  color: #fff;
  justify-content: center;
  height: 408px;
}

.container {
  display: flex;
  justify-content: center;
  align-items: center;
  column-gap: 30vw;
}

.links {
  margin: 24px;
}

.logo {
  img {
    display: block;
    margin-left: 0px;
  }
}

.navigations {
  display: flex;
  flex-wrap: wrap;
  gap: 32px;
  width: 500px;
  height: 104px;


  .navigationLink {
    color: #fff;
    text-decoration: none;
    font-size: 20px;
    white-space: nowrap;
  }
}

.greenButton {
  margin: 50px 24px 0 24px;
  white-space: nowrap;
}

.navigationLink:hover {
  color: #7FCC8F;
}
```suggestion
.footer {
  display: flex;
  align-items: center;
  background-color: #000;
  color: #fff;
  padding: 96px;
  gap: 96px;
}

.logo {
  img {
    display: block;
    margin-left: 0px;
  }
}

.navigations {
  display: flex;
  flex-wrap: wrap;
  margin-left: auto;
  gap: 32px;

  .navigationLink {
    color: #fff;
    text-decoration: none;
    font-size: 24px;
    white-space: nowrap;
  }
}

.greenButton {
  margin: 24px;
  white-space: nowrap;
}

.navigationLink:hover {
    color: #7FCC8F;
  }
```
ウィンドウ幅狭くしたら崩れちゃうけどどうかな？
良さそうだったらこれをいじってみて

2024-03-23 18:12 UTC, batora9 commented on src/components/Footer/Footer.tsx
> +    </footer>
```suggestion
    <footer className={style.footer}>
      <div className={style.container}>
        <div className={style.links}>
          <div className={style.logo}>
            <Link href='/'>
              <img
                src='/logos/Maximum-logo-white.svg'
                alt='Maximum'
                width={334}
                height={84}
              />
            </Link>
          </div>
          <div className={style.greenButton}>
            <LinkButton href='/join' variant='green'>
              入会案内はこちら
            </LinkButton>
          </div>
        </div>
        <nav className={style.navigations}>
          <Link href='/about' className={style.navigationLink}>
            About
          </Link>
          <Link href='/news' className={style.navigationLink}>
            News
          </Link>
          <Link href='#' className={style.navigationLink}>
            Join
          </Link>
          <Link href='/achievements' className={style.navigationLink}>
            Achievements
          </Link>
          <Link href='/contact' className={style.navigationLink}>
            Contact
          </Link>
          <Link href='/faq' className={style.navigationLink}>
            Q&amp;A
          </Link>
          <Link
            href='https://blog.maximum.vc'
            target='_blank'
            rel='noopener noreferrer'
            className={style.navigationLink}
          >
            Blog
            <MdArrowOutward />
          </Link>
          <Link
            href='https://x.com/Maximum03400346'
            target='_blank'
            rel='noopener noreferrer'
            className={style.navigationLink}
          >
            <SiX size={24} />
          </Link>
          <Link
            href='https://github.com/saitamau-maximum'
            target='_blank'
            rel='noopener noreferrer'
            className={style.navigationLink}
          >
            <SiGithub size={24} />
          </Link>
        </nav>
      </div>
    </footer>
```
こっちも

2024-03-24 15:56 UTC, sor4chi requested changes
お願いします

2024-03-24 15:56 UTC, sor4chi commented on src/components/Footer/Footer.module.scss
> +  margin-left: auto;
この行いらなさそう
代わりにFigma通り`width: 500px`を追加しておこう

2024-03-24 15:56 UTC, sor4chi commented on src/components/Footer/Footer.module.scss
> +  gap: 96px;
figmaによるとfooterは高さ407px固定らしいんだけど、目分量で`height: 400px`を設定しよう
paddingは消しちゃって大丈夫そう
gapはFigma情報だと`112px`になってるんだけど俺見てる場所間違えてたりする...？

2024-03-24 15:59 UTC, sor4chi requested changes
これも追加で！

2024-03-24 15:59 UTC, sor4chi commented on src/components/Footer/Footer.tsx
> +        </div>
そもそもここ囲う必要ないかも
```suggestion
        <LinkButton href='/join' variant='green'>
          入会案内はこちら
        </LinkButton>
```

2024-03-24 15:59 UTC, sor4chi commented on src/components/Footer/Footer.tsx
> +      <div>
ここに`display: flex`と`flex-direction: column`と`align-items: center`と`gap: 50px`を持ったクラスを作って設定しましょう

2024-03-25 08:56 UTC, sor4chi requested changes

2024-03-25 08:56 UTC, sor4chi commented on src/components/Footer/Footer.module.scss
> +  width: 500px;
ここにあった`flex-wrap: warp`消しちゃうと動かなくなるんだけど戻せる？
もしかして見た目変になった？

2024-03-26 12:08 UTC, shigekk commented on src/components/Footer/Footer.module.scss
> +  width: 500px;
僕もflex-wrap: warpはあった方がいいかと思ったのでもどしました．
もどしました．

2024-03-26 14:30 UTC, a01sa01to approved these changes
レスポンシブ対応ここではまだやらないんだっけ？ やらないなら OK
(やる想定ならめっちゃ崩れてるのでダメ)

2024-03-26 14:43 UTC, sor4chi commented
泊まるので別でやりましょう
cc @yukikamome316

2024-03-27 09:17 UTC, batora9 approved these changes

2024-03-27 09:18 UTC, merged