ボタンサイズを変更できるようにした
saitamau-maximum/public-website pull request #55
Opened 2024-03-23 16:07 UTC by shigekk

2024-03-23 16:16 UTC, batora9 approved these changes
いいとおもう

2024-03-24 10:10 UTC, batora9 commented
@yukikamome316 レビューお願いします

2024-03-24 10:34 UTC, a01sa01to requested changes

2024-03-24 10:34 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.module.css
> +}
ちょっと値はずれるけど  `padding: 1em 2em` とかで全部まとめられそう？

2024-03-24 10:34 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.module.css
> +}
こっちはたぶん `0.5em 3em` かな

2024-03-24 10:34 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.stories.tsx
large, small のケースも追加していただけると :pray:

2024-03-24 13:46 UTC, yukikamome316 requested changes

2024-03-24 13:46 UTC, yukikamome316 commented on src/components/LinkButton/LinkButton.module.css
![image](https://github.com/saitamau-maximum/public-website/assets/32415464/ca61bad0-3945-4c0d-ac8b-982e3439e5d8)
![image](https://github.com/saitamau-maximum/public-website/assets/32415464/ec8b431a-45c1-4e00-b508-19a9cf06224f)

smallのときの縦横比はmediumやlargeに合わせないで、要件定義通りくらいのpaddingに合わせてあげるといいかもしれない

2024-03-24 13:50 UTC, yukikamome316 commented on src/components/LinkButton/LinkButton.module.css
primary/secondaryも同様に！
(そもそもprimary/secondaryじゃなくて、green/grayに名前を変えるべきかもしれない)

2024-03-27 13:11 UTC, sor4chi approved these changes
めっちゃいい！できる人のコードや

2024-03-27 14:48 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.module.css
> +
ここ `.greenButton` とかぶってるので消してよさそう

2024-03-27 14:48 UTC, a01sa01to commented on src/components/LinkButton/LinkButton.module.css
> +}
こっちも

2024-03-27 15:05 UTC, shigekk commented on src/components/LinkButton/LinkButton.module.css
確認お願いします

2024-03-27 15:08 UTC, yukikamome316 approved these changes
いいね！お疲れ様！

2024-03-27 15:10 UTC, a01sa01to approved these changes
おつかれ～

2024-03-27 15:10 UTC, merged