feat: 最小限のトップページを作成
saitamau-maximum/public-website pull request #56
Opened 2024-03-24 10:04 UTC by batora9

トップページの2枚の画像はまだ確定していないためboxのままにしています。News（新着情報）と過去の実績は端折った最低限のページです。CSSの書き方にいろいろ修正できるところあると思うのでレビューお願いします。

※ヘッダーをすべてのページで表示させ、画面サイズに応じてヘッダーのスタイルを変更できるようにしています。ただし、ハンバーガーメニューに関してはまだ実装ができていない状況です。

2024-03-24 10:53 UTC, a01sa01to requested changes

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +  }
.span と .bold に分けたほうが書き方的にはいいかも？

```suggestion
  .bold {
    font-weight: bold;
  }

  .span {
    color: #47B660;
  }
```

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.tsx
> +            (週１回)の２つの活動を行っています。
半角にする

```suggestion
            (週2回)と<span className={style.boldspan}>Web研究会</span>
            (週1回)の２つの活動を行っています。
```

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.tsx
> +              </LinkButton>
改行されないほうがよさそう？ (でもこれは後で対応予定かな？)
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/61728ef9-f593-4893-98c5-6734714d90f5)

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +@media screen and (min-width: 1280px){
メディア種別は消して OK

```suggestion
@media (min-width: 1280px) {
```

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
全体的に: [メディアクエリは本当に必要ですか？ - MDN](https://developer.mozilla.org/ja/docs/Learn/CSS/CSS_layout/Media_queries#%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%E3%82%AF%E3%82%A8%E3%83%AA%E3%83%BC%E3%81%8C%E6%9C%AC%E5%BD%93%E3%81%AB%E5%BF%85%E8%A6%81%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F)

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +    max-width: 1080px;
768px 以下なのに width: 100%, max-width: 1080px するのは無意味
メディアクエリをまとめるか、ここの max-width を消すか

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +    font-size: 20px;
全体: font-size は rem にしよう

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +@media screen and (min-width: 1280px){
メディアクエリの値は Sass 変数とかにまとめて全体で参照できるようにしたいかも？

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.module.css
> +    color: #47B660;
色もまとめたいかな

2024-03-24 10:53 UTC, a01sa01to commented on src/app/page.tsx
> +          <img src='images/hero.png' alt='Hero' className={style.heroImage} />
```suggestion
          <img src='/images/hero.png' alt='Hero' className={style.heroImage} />
```

2024-03-24 11:04 UTC, a01sa01to commented on src/app/page.module.css
メディアクエリすると場合分け地獄になるしコードも読みづらくなるので...

2024-03-24 12:00 UTC, batora9 commented on src/app/page.tsx
> +              </LinkButton>
改行はFigmaの要件通りです

2024-03-24 13:26 UTC, a01sa01to commented on src/app/page.tsx
> +              </LinkButton>
あそうなの？みてなかったわ

2024-03-24 13:27 UTC, a01sa01to commented on src/app/page.module.css
> +@media screen and (min-width: 1280px){
全箇所

2024-03-24 16:02 UTC, sor4chi commented
いいね、めっちゃちゃんとしたサイト感出てきた

2024-03-25 01:58 UTC, a01sa01to commented on src/app/page.tsx
> +              </span>
clsx が入ってるので `import clsx from 'clsx'` したら

```suggestion
              <span className={clsx(style.span, style.bold)}>ICPC</span>
```

で OK

2024-03-25 01:58 UTC, a01sa01to commented on src/app/page.tsx
> +              </span>
ほかのところも

2024-03-25 01:58 UTC, a01sa01to commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
`&nbsp;` いらない気するけどな... 
ここに入れるなら全 span (highlight?) の前後に入れたほうがいいのではという気持ち

2024-03-25 10:42 UTC, batora9 commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
Figmaの書き方をそっくり真似ました

2024-03-26 01:13 UTC, a01sa01to commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
@hana-rs @sor4chi どう思いますか

2024-03-26 01:49 UTC, hana-rs commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
太緑字だけで強調できそうなので詰めてもいいかなと思います。

2024-03-26 03:23 UTC, sor4chi commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
自分は詰めない方が見やすくていいと思うけどね...

2024-03-26 03:23 UTC, sor4chi commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
Discordでも議論に上がってたけど、緑文字がリンクに見えるの確かに問題だなという

2024-03-26 07:46 UTC, a01sa01to commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
自分も詰めないほうが見やすいとは思うけどどっちかには統一したいよなという気がある
緑文字がリンクに見えるのは確かに問題で、単に太字にするだけ (色変えず) でもありかもなぁと思っている
(@batora9 @hana-rs  お任せします)

2024-03-26 10:38 UTC, sor4chi commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
> 緑文字がリンクに見えるのは確かに問題で、単に太字にするだけ (色変えず) でもありかもなぁと思っている
same

2024-03-26 10:56 UTC, batora9 commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
> 自分も詰めないほうが見やすいとは思うけどどっちかには統一したいよなという気がある 緑文字がリンクに見えるのは確かに問題で、単に太字にするだけ (色変えず) でもありかもなぁと思っている (@batora9 @hana-rs お任せします)

@a01sa01to 
どっちかに統一とはほかにどの部分（テキスト）が当てはまりますか？

2024-03-26 11:45 UTC, a01sa01to requested changes

2024-03-26 11:45 UTC, a01sa01to commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
？

2024-03-26 11:45 UTC, a01sa01to commented on src/app/page.tsx
> +              に向けて
ここも `&nbsp;` 追加で

2024-03-26 11:45 UTC, a01sa01to commented on src/components/Header/Header.module.scss
> +@media screen and (max-width: 1200px) {
```suggestion
@media (max-width: 1200px) {
```

2024-03-26 11:45 UTC, a01sa01to commented on src/components/Header/Header.module.scss
> +  }
```suggestion
    display: none;
  }
```

2024-03-26 11:45 UTC, a01sa01to commented on src/components/Header/Header.module.scss
>  }
同じ部分は省略して OK
(`@media` がついてないスタイルが適用されるので)

2024-03-26 13:54 UTC, a01sa01to commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
？

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +}
```suggestion
.heroImage {
  width: 100%;
  height: 60vh;
  object-fit: cover;
}

@media (max-width: $heroImage-change-width) {
  .heroImage {
    height: 100%;
  } 
}
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
かぶってるので消す

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +}
かぶってるので消して OK

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
.main {
  padding-top: 72px;
  flex-direction: column;
  background-color: $background-color;
}

/* 画面幅が768px以下の場合のスタイル */
@media (max-width: $tablet-width) {
  .main {
    padding-top: 64px;
  }
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +@media (min-width:768px) {
これ消して `max-width: $tablet-width` だけにして、 L202-346 は外に出しちゃっていいかも (以下、そうした場合にかぶるところをメモしておきます)

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
まとめると消せます

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
  .breadcrumb {
    height: 28px;
  }
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
  .breadcrumbLink {
    font-size: 0.75rem; // 12px
  }
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
消せる

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
  .contentTitle {
    margin: 20px;
    font-size: 1.25rem; // 20px
  }
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
  .aboutText {
    margin: 24px;
    font-size: 1rem; // 16px
  }
```

2024-03-26 14:18 UTC, a01sa01to commented on src/app/page.module.scss
> +  }
```suggestion
  .activityCPtitle h2 {
    font-size: 1.25rem; // 20px
  }
```

2024-03-27 13:17 UTC, sor4chi commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
この件解決したってことでいいよね？
@batora9

2024-03-27 13:18 UTC, batora9 commented on src/app/page.tsx
> +              &nbsp;や&nbsp;
はい

2024-03-28 03:06 UTC, sor4chi approved these changes

2024-03-28 14:43 UTC, yukikamome316 approved these changes

2024-03-28 14:49 UTC, a01sa01to approved these changes

2024-03-28 15:13 UTC, merged