Feat/カードコンポーネントサイズ変更
saitamau-maximum/public-website pull request #59
Opened 2024-03-24 14:24 UTC by nakamuraitsuki

縦幅はもともと自動だったので、widthのみ変更できるようにしました。正しくない値が入った場合には100%になるようになっているはずです。
よろしくお願いします。

2024-03-24 15:27 UTC, yukikamome316 requested changes

2024-03-24 15:27 UTC, yukikamome316 commented on src/components/Card/Card.tsx
> +    <Link href={to} className={style.card} style={{ width }}>
stringとしてcardWidthを受け取るのではなく、`React.CSSProperties | undefined`としてstyleに渡す内容を受け取ってしまうのがよさそう

2024-03-25 01:49 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +  customStyle,
ふつうに style でいいと思う

2024-03-25 01:49 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +  customStyle?: React.CSSProperties | undefined;
? をつけてる時点で optional (つまり undefined も含まれている) ので、
```suggestion
  customStyle?: React.CSSProperties;
```
で OK

2024-03-25 02:38 UTC, nakamuraitsuki commented on src/components/Card/Card.tsx
> +  customStyle,
importしているstyleと被ってしまうことを避けるために変えてみました。
ここはかぶっていても大丈夫ですか？

2024-03-25 05:04 UTC, a01sa01to commented on src/components/Card/Card.tsx
> +  customStyle,
あーなるほど...
それなら props を style にして、 Card 引数側で
```suggestion
  style: customStyle,
```
にすれば親で style として渡してもこっちでは customStyle として受け取れます

2024-03-25 07:42 UTC, nakamuraitsuki commented on src/components/Card/Card.tsx
> +  customStyle,
ありがとうございます

2024-03-27 08:56 UTC, yukikamome316 approved these changes
LGTM

2024-03-27 09:12 UTC, a01sa01to approved these changes

2024-03-27 09:12 UTC, merged