Feat/pages
saitamau-maximum/public-website pull request #6
Opened 2024-02-23 10:19 UTC by batora9

2024-02-23 13:38 UTC, yukikamome316 requested changes
細かいけどインデントの個数は統一してほしい！
`yarn lint:fix && yarn format` コマンドで一発だ

2024-02-24 05:43 UTC, yukikamome316 approved these changes
後は大丈夫そう

2024-02-24 06:03 UTC, sor4chi commented
横からレビュー失礼するんだけど、　next.jsには確かtitle template機能があるはずなので調べてみてほしい
https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

2024-02-24 06:07 UTC, batora9 commented
@yukikamome316 title tempどうしますか？

2024-02-24 06:11 UTC, yukikamome316 commented
> @yukikamome316 title tempどうしますか？

いいね使ってみよう

2024-02-24 07:52 UTC, a01sa01to approved these changes

2024-02-24 15:08 UTC, merged