feat: フッターのレスポンシブデザイン
saitamau-maximum/public-website pull request #61
Opened 2024-03-27 13:02 UTC by batora9

「入会案内はこちら」ボタンのサイズは後で変えます。（まだ https://github.com/saitamau-maximum/public-website/pull/55 がmergeされてないので）

2024-03-27 15:52 UTC, sor4chi commented
ボタン更新してもろて

2024-03-28 08:31 UTC, sor4chi approved these changes
いいね

2024-03-28 14:37 UTC, yukikamome316 requested changes
![image](https://github.com/saitamau-maximum/public-website/assets/32415464/f43e4c29-461f-498b-adde-7cb7aeef8515)
この3つが全てBlogに遷移するリンクになってしまってる

2024-03-29 01:17 UTC, a01sa01to approved these changes

2024-03-29 12:43 UTC, batora9 commented
@yukikamome316 お願いします

2024-03-30 11:08 UTC, yukikamome316 approved these changes

2024-03-30 11:17 UTC, merged