とりあえずglobal.cssに追加
saitamau-maximum/public-website pull request #62
Opened 2024-03-28 18:32 UTC by shigekk

僕が調べた限りでは
next fontでYu Gothic使ったり
無料でダウンロードしたりするのは難しそうです
いやいや出来るよ　ということがあったら教えてください

2024-03-29 06:54 UTC, sor4chi commented
[ウェブサイトでローカルフォントの「游ゴシック」はもう使えない](https://note.com/onopko/n/n804e69b0ac96)

> 従来MacとWindows共通の日本語フォントとして利用されてきた「游ゴシック」ですが、最近のブラウザは個人情報保護の観点からローカルフォントの使用を制限し始めています。Macの主要ブラウザではもはや「游ゴシック」を表示できない原因は、このフォントがシステムフォントに該当しないためです。今後ウェブサイトで「游ゴシック」を使用する場合は、ウェブフォントを利用する必要があると説明します。

-> YuGothicを使いたい場合はWebフォントを使う必要がある

無料でYuGohicを使えるWebフォントサービスは調べた限りないかも

![Screenshot 2024-03-29 at 15 53 58](https://github.com/saitamau-maximum/public-website/assets/80559385/f940d2af-4205-44f3-ad1b-4df04f976cd6)

2024-03-29 06:54 UTC, sor4chi commented
システムフォントで完結する？それともNoto Sansとかもっと有名で無料なフォントに移行する？

2024-04-05 13:06 UTC, shigekk commented
できてないみたいですが
どこが間違ってるでしょうか
GoogleFontsのimportができてなさそう

2024-04-05 14:14 UTC, sor4chi requested changes

2024-04-05 14:14 UTC, sor4chi commented on src/app/layout.tsx
> +import { Inter, GoogleFont } from 'next/font/google';
多分Noto_Sans_JPってのがあるはず、それしかimportしなくて良かった記憶がある

2024-04-05 14:14 UTC, sor4chi commented on src/app/layout.tsx
> +  subsets: ['japanese'],
subsets japaneseにすると日本語以外のフォントが勝手に排除されてしまう（英語とか数字とか）と思うので、subsetはこの4択でjapaneseはないんじゃないか？
![Screenshot 2024-04-05 at 23 11 31](https://github.com/saitamau-maximum/public-website/assets/80559385/29a1aaba-020a-4241-a365-671b8a85752d)

subsetsはlatinだけで良さそう

2024-04-05 16:23 UTC, sor4chi requested changes
良さそう！あとformatしてくれたら！

2024-04-05 17:52 UTC, sor4chi approved these changes
お疲れい！

2024-04-05 19:36 UTC, batora9 approved these changes
OK

2024-04-09 07:53 UTC, merged