feat: トップページに新着情報を載せる
saitamau-maximum/public-website pull request #67
Opened 2024-04-03 10:46 UTC by batora9

2024-04-03 10:50 UTC, sor4chi commented on src/components/Card/Card.module.css
>      border: 1px solid #ccc;
cardのborderって必要？
他にborderがあるカードがあって、それと共通化したらこうなったみたいなかんじ？

2024-04-03 10:52 UTC, batora9 commented on src/components/Card/Card.module.css
>      border: 1px solid #ccc;
カードコンポーネントに関しては @nakamuraitsuki

2024-04-03 11:03 UTC, a01sa01to requested changes

2024-04-03 11:03 UTC, a01sa01to commented on src/components/news-list/news-list.tsx
> +  }
splice は in-place で要素を書き換えちゃうので個人的には使いたくないかも

```suggestion
  if (docs.length === 0) {
    return <p className={style.newsEmpty}>新着情報はありません</p>;
  }
  const topDocs = docs.slice(0, 3);
```

2024-04-03 11:03 UTC, a01sa01to commented on src/components/news-list/news-list.tsx
> +          />
slug, content 以外の frontmatter 要素は存在しない可能性もあるので fallback させる値とかあるといいかも

2024-04-03 12:08 UTC, nakamuraitsuki commented on src/components/Card/Card.module.css
>      border: 1px solid #ccc;
確認したところ、カード作成当初から混入していた不要なborderでした。
おそらく、storybookの白背景と区別するために付け、そのままにしてしまったものと思われます。
お騒がせしてすみませんでした。

2024-04-03 12:38 UTC, batora9 commented on src/components/news-list/news-list.module.scss
> +@media (min-width: 768px){
ファイルにまとめるとはどういうことですか？

`$tablet-width: 768px;`ということではないのか...?

2024-04-03 14:27 UTC, batora9 commented on src/components/Card/Card.module.css
>      border: 1px solid #ccc;
消していいのか？

2024-04-04 21:43 UTC, batora9 commented on src/components/news-list/news-list.tsx
> +          />
カードコンポーネントが新着情報でしか使わないため`NewsCard`に改名し、fallback値はなしにしようという風に決まりました

2024-04-05 00:14 UTC, sor4chi requested changes

2024-04-05 00:14 UTC, sor4chi commented on src/components/news-list/news-list.tsx
> +
SSGでは`throw new Error('エラーの理由')`と書くことでビルドを失敗させることができます。
https://discord.com/channels/1036566020070060032/1102523386577571863/1225585712284303431
Asaさんが言っている通り、markdownはそもそもfrontmatterを何も書かなくてもなりたってしまうので、何もfrontmatterが設定されていないNewsのマークダウンファイルがあった場合にデザインがこのままだと崩れてしまうんですよね。
なのでここでfrontmatterにちゃんと値が入っていることを確認するバリデーションをかけ、もしなかったらErrorをthrowしましょう

2024-04-05 01:23 UTC, sor4chi approved these changes
とてもよい

2024-04-05 01:43 UTC, a01sa01to commented on src/components/Footer/Footer.module.scss
> +@use 'src/app/_variables';
これってちゃんと使えてるの？

基本こっちのはず

```suggestion
@use 'src/app/variables';
```

2024-04-05 01:43 UTC, a01sa01to commented on src/components/news-list/news-list.module.scss
> +@use 'src/app/_variables';
こっちも

2024-04-05 01:43 UTC, a01sa01to commented on src/components/news-list/news-list.tsx
> +    throw new Error('frontmatterに未記入の項目があります');
何が足りないか書いてあげると親切かなぁと思うなど

2024-04-05 02:32 UTC, sor4chi commented on src/components/news-list/news-list.tsx
> +    throw new Error('frontmatterに未記入の項目があります');
そこまでは必要なさそうだけど、newsのマークダウンだよとかこのslugのマークダウンがダメだったよみたいな理由あると良さそう

2024-04-05 03:12 UTC, batora9 commented
![image](https://github.com/saitamau-maximum/public-website/assets/132897821/e2e31c3d-1e62-4fcd-b10d-1b1dcac000ec)

こういう風に表示してくれるようにしました

2024-04-05 03:33 UTC, a01sa01to approved these changes

2024-04-05 03:33 UTC, a01sa01to commented on src/components/news-list/news-list.tsx
> +    );
`key as keyof typeof doc.frontmatter` すごいことしてるなw

2024-04-05 03:51 UTC, sor4chi approved these changes
よい
型パズル大変そうなのでfrontmatterのvalidateはmarkdown-processor持ちにしてもいいかもしれない

2024-04-05 03:54 UTC, merged