feat: /newsのデザイン
saitamau-maximum/public-website pull request #69
Opened 2024-04-06 06:51 UTC by batora9

ページネーションはできていません（あとでやる）
とりあえず一覧で並べるようにしました

2024-04-06 07:16 UTC, sor4chi requested changes

2024-04-06 07:16 UTC, sor4chi commented on src/components/LinkCard/LinkCard.tsx
このコンポーネント、名前をNewsLinkCardにした方が良さそう

2024-04-06 07:16 UTC, sor4chi commented on src/app/news/page.module.scss
> +$span-color: #47B660;
なんかfigmaより色明るくない？

2024-04-06 07:16 UTC, sor4chi commented on src/components/LinkCard/LinkCard.tsx
Figmaとモバイル時のデザインが違う気がする！
![Screenshot 2024-04-06 at 16 13 16](https://github.com/saitamau-maximum/public-website/assets/80559385/e1589339-fbbf-4c0a-bbc5-4560e0bb755d)
![Screenshot 2024-04-06 at 16 13 37](https://github.com/saitamau-maximum/public-website/assets/80559385/ad5c12f1-5117-449f-a6f9-3d1f5bb6e548)

2024-04-06 07:16 UTC, sor4chi commented on src/components/news-page-list/news-page-list.tsx
> +          date={doc.frontmatter.updatedAt.replace(/-/g, '/').slice(0, 7)}
```suggestion
          date={new Date(doc.frontmatter.updatedAt).toLocaleDateString("ja-JP", {year: "numeric",month: "2-digit"})
```

2024-04-06 07:16 UTC, sor4chi commented on src/components/news-page-list/news-page-list.tsx
> +          date={doc.frontmatter.updatedAt.replace(/-/g, '/').slice(0, 7)}
実は`Date.toLocaleDateString`でかけます

2024-04-06 07:35 UTC, a01sa01to requested changes

2024-04-06 07:35 UTC, a01sa01to commented on src/app/news/page.module.scss
> +$background-color: #F1F1F1;
ここら辺の共通してるやつは `_variables.scss` にまとめよう (少なくとも `src/app/page.module.scss` にあったので)

2024-04-06 07:35 UTC, a01sa01to commented on src/components/LinkCard/LinkCard.tsx
> +          <h2 className={style.title}>{title}</h2>
h2 よくない気がする？

ref: https://github.com/saitamau-maximum/public-website/pull/48#discussion_r1532045645, https://github.com/saitamau-maximum/public-website/pull/52#discussion_r1535108443

2024-04-06 07:35 UTC, a01sa01to commented on src/components/news-page-list/news-page-list.tsx
> +          content='AtCoder社の協力により◯年ぶりにMaximum主催の競技プログラミングコンテストを主催しました'
ここって description じゃないの？

2024-04-06 21:58 UTC, batora9 commented on src/components/news-page-list/news-page-list.tsx
> +          content='AtCoder社の協力により◯年ぶりにMaximum主催の競技プログラミングコンテストを主催しました'
修正し忘れてました...

2024-04-09 13:52 UTC, a01sa01to approved these changes
カラーコードの大文字小文字統一したい気もするけど Linter に任せればいい気もするので後でいいや

2024-04-09 14:38 UTC, sor4chi approved these changes
諸々突っ込みたいところあるけどリファクタリング後でできるのでとりあえずOK

2024-04-09 18:06 UTC, merged