feat: Dynamic hero image
saitamau-maximum/public-website pull request #71
Opened 2024-04-09 01:28 UTC by batora9

hero画像にテキストを表示させたり、ぼかしをかけられるようにしてコンポーネントとして統一させました

2024-04-09 01:37 UTC, a01sa01to requested changes

2024-04-09 01:37 UTC, a01sa01to commented on src/components/DynamicHeroImage/DynamicHeroImage.tsx
> +        })}
```suggestion
        className={clsx(style.heroImage,
          blur && style.blur,
          type === 'default' && style.default,
          type === 'thumbnail' && style.thumbnail,
        )}
```

2024-04-09 01:37 UTC, a01sa01to commented on src/components/DynamicHeroImage/DynamicHeroImage.tsx
Dynamic か...？別に HeroImage だけでよくない？

2024-04-09 03:57 UTC, batora9 commented on src/components/DynamicHeroImage/DynamicHeroImage.tsx
了解です

2024-04-09 05:11 UTC, batora9 commented
`/about`にはまだ実装せずに、`/`だけとりあえず実装しました。（`/news`もまだmergeされていないためほかのページを一気にheroを実装するのはまだなのかと思いました）

2024-04-09 13:51 UTC, a01sa01to approved these changes

2024-04-09 13:51 UTC, a01sa01to commented on src/components/HeroImage/HeroImage.tsx
> +        src={type === 'default' ? '/images/hero2.png' : '/images/hero.png'}
ファイル名・ type がわかりづらいので (優先度低いけど) 変えてもいいかも

2024-04-09 14:38 UTC, sor4chi commented
高さの違い直せそう？ @batora9

2024-04-09 17:34 UTC, batora9 commented
@sor4chi それはHeroImageコンポーネントのことですか？
現aboutページのheroはあとで置き換えます

2024-04-09 17:56 UTC, sor4chi commented
おけ!そういうことね!

2024-04-09 18:46 UTC, sor4chi commented
@batora9 コンフリクトしてるっぽい

2024-04-10 09:06 UTC, sor4chi approved these changes

2024-04-10 14:50 UTC, merged