feat/実績ページの仕上げ
saitamau-maximum/public-website pull request #76
Opened 2024-04-10 06:07 UTC by nakamuraitsuki

よろしくお願いいたします。

2024-04-10 07:24 UTC, a01sa01to requested changes

2024-04-10 07:24 UTC, a01sa01to commented on docs/achievement/icpc.md
> +iconUrl: "https://acm.cs.unlv.edu/img/busImg.PNG"
外部サイトの画像は URL が勝手に変わる可能性もあるので、適当にダウンロードしちゃっていいかも

2024-04-10 07:24 UTC, a01sa01to commented on docs/achievement/isucon.md
> +subtitle: "Iikanji Spped Up Contest"
```suggestion
subtitle: "Iikanjini Speed Up Contest"
```

2024-04-10 07:24 UTC, a01sa01to commented on docs/achievement/isucon.md
> +iconUrl: "https://avatars.githubusercontent.com/u/9019510?s=280&v=4"
GitHub のほうはそのままでいいかも

2024-04-10 07:24 UTC, a01sa01to commented on docs/achievement/ute-1.md
> +subtitle: "ULTRA TAMAGO ENGINEER No.1"
しらなかったw (not a change request)

2024-04-10 07:24 UTC, a01sa01to commented on public/images/ISUCON.png
@sor4chi @hana-rs 「Iikanjini」だよ

2024-04-10 07:24 UTC, a01sa01to commented on src/app/achievements/page.tsx
> +import { FaArrowRight } from 'react-icons/fa';
たしかほかのところで react-icons/md を使ってたから md で同じようなアイコンがいいかも？

2024-04-10 07:39 UTC, batora9 requested changes

2024-04-10 07:44 UTC, batora9 commented
@nakamuraitsuki #71 がmergeされたらHero設定しちゃっていい？

2024-04-10 08:37 UTC, nakamuraitsuki commented on src/app/achievements/page.tsx
> +import { FaArrowRight } from 'react-icons/fa';
figma確認したところ、react-icons/fiだったので、そちらに変更しておこうと思うのですか、どうでしょう

2024-04-10 08:37 UTC, nakamuraitsuki commented on src/app/achievements/page.tsx
> +import { FaArrowRight } from 'react-icons/fa';
figma確認したところ、react-icons/fiだったので、そちらに変更しておこうと思うのですか、どうでしょう

2024-04-10 08:44 UTC, nakamuraitsuki commented on src/app/achievements/page.tsx
> +            </div>
成績はこちら→　の色は緑色のままでよい？
ホバーした時には外枠に影つける感じでよい？

2024-04-10 09:48 UTC, sor4chi requested changes
色々一気に指摘しちゃってすみません！お願いします！

2024-04-10 09:48 UTC, sor4chi commented on src/app/achievements/page.tsx
> +        ))}
この部分、Achivement CardとかAcheivement ListみたいにNewsのコンポーネントの分け方みたいにコンポーネント化しちゃった方が良さそう！

2024-04-10 09:48 UTC, sor4chi commented on src/app/achievements/page.tsx
> +      </div>
![Screenshot 2024-04-10 at 18 34 22](https://github.com/saitamau-maximum/public-website/assets/80559385/e2365e47-dd4e-4e43-9829-c7c20c27ea26)
見た目上は「成績を見る」がリンクだけど、これだとクリックできる範囲がめちゃ狭くなってしまうので、カード全体をリンクにしちゃっていい気がする！

2024-04-10 09:48 UTC, sor4chi commented on src/components/Article/Article.module.css
> +    font-size: 18.55px;
`oo.xx px`がもしFigmaにあったら、基本Figmaの方のミスなので無視して整数値で置き換えちゃって大丈夫です！

例えば`18px`だとして`1.125rem`とするのが良いかと思います

2024-04-10 09:48 UTC, sor4chi commented on src/components/Article/Article.module.css
> +    width: 799.8px;
↑を治すとこれが`width: 100%`で良くなります

2024-04-10 09:48 UTC, sor4chi commented on src/app/achievements/[slug]/slug-styles.module.css
> +    padding-left: 20px;
![Screenshot 2024-04-10 at 18 40 30](https://github.com/saitamau-maximum/public-website/assets/80559385/4aaf2892-9729-45f2-bdaf-8de62216460f)
![Screenshot 2024-04-10 at 18 40 10](https://github.com/saitamau-maximum/public-website/assets/80559385/91fe74d3-3043-42dd-b37c-1cbaae369b5d)

こんな感じにpadding-rightも設定してあげた方が均等に余白できるので良さそう

2024-04-10 09:48 UTC, sor4chi commented on src/app/achievements/[slug]/slug-styles.module.css
> +    width: 808px;
↑を治すとこれが`width: 100%`で良くなります

2024-04-10 09:48 UTC, sor4chi commented on src/app/achievements/[slug]/slug-styles.module.css
> +    width:745px;
↑を治すとこれが`width: 100%`で良くなります

2024-04-10 09:48 UTC, sor4chi commented on src/components/Toc/Toc.module.css
> +    width: 20rem;
widthには基本rem使わなくていいので`width: 360px`にしましょう！
`rem`は文字相対サイズなので文字サイズのデバイス設定に従ってスケールする必要がないという理由です！

2024-04-10 09:48 UTC, sor4chi commented on src/components/Toc/Toc.module.css
> +    margin-bottom: 7px;
ここら辺、7px -> 8px, 13px -> 16pxにしましょう

2024-04-10 09:48 UTC, sor4chi commented on src/components/Toc/Toc.module.css
> +    font-size: 0.95rem;
activeスタイルを設定してくれたのは良いことなのですが、font-sizeを可変にするのはあまりよろしくありません。
今回は変化が0.95と微妙なのでそこまで影響がわからないと思うのですが、文字サイズが変わるとそのサイズ変化に応じてその下の要素が上下にシフトしてしまう可能性があります。
activeスタイルはつけるなら文字色を変えるとか、背景色を入れるとか、アンダーラインをつけるとかにしましょう！

2024-04-10 18:34 UTC, batora9 commented
@nakamuraitsuki レスポンシブ対応までできそう？厳しかったら共著するけど

2024-04-11 02:23 UTC, a01sa01to commented on src/app/achievements/page.tsx
> +import { FaArrowRight } from 'react-icons/fa';
ん－基本的にアイコンは揃えたいかな～ (デザインは統一されているほうが良いとされるので)

2024-04-11 05:32 UTC, nakamuraitsuki commented
![スクリーンショット 2024-04-11 141851](https://github.com/saitamau-maximum/public-website/assets/132897891/017f5d0d-7b04-47ee-8e53-4673f5780cf6)
なんか詰め詰めになっちゃうのは、僕のスクリーンがちっこいからでしょうか

2024-04-11 05:35 UTC, nakamuraitsuki commented
> @nakamuraitsuki レスポンシブ対応までできそう？厳しかったら共著するけど

スマホに対応させるってこと？
出来ればお願いしたいかもです

2024-04-11 06:44 UTC, batora9 commented
@nakamuraitsuki りょうかい。きりがいいところで呼んでくれればやる

2024-04-12 07:09 UTC, batora9 commented
@nakamuraitsuki @sor4chi @a01sa01to レスポンシブ対応＋修正しました

2024-04-12 08:04 UTC, sor4chi requested changes
あと少し！

2024-04-12 08:04 UTC, sor4chi commented on src/components/Toc/Toc.tsx
> +};
```suggestion
const renderTocItems = (items: TocItem[]) => {
  return items.map((item, index) => (
    <div
      key={index}
      className={style.tocItem}
      style={{
        marginLeft: `${item.depth * 7.5}px`,
        borderLeft: `${item.depth > 1 ? '1.5px solid #d3d3d3' : 'none'}`,
      }}
    >
      <Link className={style.value} href={`#${item.data.id}`}>
        {item.value}
      </Link>
      {item.children.length > 0 && renderTocItems(item.children)}
    </div>
  ));
};

const Toc: React.FC<{ tocData: TocItem[] }> = ({ tocData }) => {
  return (
    <div className={style.container}>
      <h3 className={style.title}>目次</h3>
      <hr className={style.line} />
      {renderTocItems(tocData)}
    </div>
  );
};
```

2024-04-12 08:04 UTC, sor4chi commented on src/components/Toc/Toc.tsx
> +};
どうでもいい話だけどこのrender関数のスコープは大域でもいい気がする！

2024-04-12 08:04 UTC, sor4chi commented on src/components/Article/Article.module.css
> +    font-size: 1.125;
これ単位rem?

2024-04-12 09:03 UTC, a01sa01to requested changes
フォーマットをかけよう！ (`npm run lint:fix` + `npm run format`)

2024-04-12 09:38 UTC, a01sa01to commented
> フォーマットをかけよう！ (`npm run lint:fix` + `npm run format`)

これ、css/scss には効かないのか...

2024-04-12 09:58 UTC, batora9 commented
いろいろ追加で修正しました
すみません

2024-04-12 13:37 UTC, sor4chi commented
@nakamuraitsuki ビルド失敗していそうですが修正できそうですか？

2024-04-12 14:59 UTC, sor4chi approved these changes
よき！

2024-04-12 23:29 UTC, a01sa01to approved these changes

2024-04-12 23:34 UTC, batora9 approved these changes
[slug]ページで https://github.com/saitamau-maximum/public-website/pull/82#discussion_r1562366611 なのとICPCのページでスタイル崩れてるとこあるけどあとでいいか

2024-04-12 23:34 UTC, merged