feat: breadcrumbの実装
saitamau-maximum/public-website pull request #77
Opened 2024-04-11 08:09 UTC by batora9

パンくずリストです

2024-04-11 08:36 UTC, sor4chi requested changes

2024-04-11 08:36 UTC, sor4chi commented on src/components/BreadCrumb/BreadCrumb.tsx
> +              <p className={styles.breadcrumbLink}>{item.title}</p>
ここなんで同じクラス重なってるんだろ
pタグが文章用のタグなので文章全体をリンクにしてるような構造になってるけど、実際は文章の一部をリンクにするのでこの場合はaタグの中に直接タイトルを入れるか、aタグの中でもう一段ネストしたいならspanを使いましょう

2024-04-11 10:17 UTC, a01sa01to requested changes

2024-04-11 10:17 UTC, a01sa01to commented on src/components/BreadCrumb/BreadCrumb.tsx
> +export const BreadCrumb: React.FC<BreadcrumbItem> = ({ items }) => {
細かいけど Breadcrumb で 1 語なので
```suggestion
export const Breadcrumb: React.FC<BreadcrumbItem> = ({ items }) => {
```
がよさそう

2024-04-11 10:17 UTC, a01sa01to commented on src/components/BreadCrumb/BreadCrumb.tsx
> +            <a href={item.href} className={styles.breadcrumbLink}>
next/link にする

2024-04-11 10:17 UTC, a01sa01to commented on src/components/BreadCrumb/BreadCrumb.tsx
> +          {index < items.length - 1 && <p className={styles.separator}>&gt;</p>}
span がよさそう (段落ではないので)

2024-04-11 10:17 UTC, a01sa01to commented on src/components/BreadCrumb/BreadCrumb.tsx
> +    <div className={styles.container}>
nav で囲ったほうがいいかも？

2024-04-12 07:26 UTC, sor4chi approved these changes
yosasou

2024-04-12 09:00 UTC, a01sa01to approved these changes

2024-04-12 09:02 UTC, batora9 commented
お忙しい中ありがとうございます

2024-04-12 09:02 UTC, merged