feat: トップページの整備
saitamau-maximum/public-website pull request #82
Opened 2024-04-12 10:21 UTC by batora9

トップページの画像の挿入とリンク指定をしました

2024-04-12 10:30 UTC, a01sa01to requested changes

2024-04-12 10:30 UTC, a01sa01to commented on public/images/top1.png
ファイル重そう、もっと解像度下げて圧縮してもいいかも

> [!TIP]
> next/image 使ってるなら勝手に最適化されるので問題ないと思ったが、 SSG であることを思い出した

2024-04-12 10:30 UTC, a01sa01to commented on src/app/page.tsx
>                </div>
リンク先、 header で隠れてしまうので main に scroll-margin を追加すると良いです

2024-04-12 23:36 UTC, batora9 commented
はいはいコンフリクト

2024-04-13 01:57 UTC, sor4chi commented
asaさんの変更反映してくれたらokです

2024-04-13 02:07 UTC, batora9 commented on src/app/page.tsx
>                </div>
mainに`scroll-margin-top: 72px;`を追加しましたが変わりません...

2024-04-13 02:22 UTC, a01sa01to commented on src/app/page.tsx
>                </div>
どこの css に追加した？ 少なくとも about の main に指定しないとだめだよ (まあほんとは全ページにやるべき)

2024-04-13 02:24 UTC, batora9 commented on src/app/page.tsx
>                </div>
`<main className={style.box}>`

ここです boxのところに追加しました

2024-04-13 05:09 UTC, a01sa01to commented on src/app/page.tsx
>                </div>
あーこれ body 直下に main がないのか
この場合だと `<div className={style.container}>` に指定するのが正しそう
あるいは `body` に `scroll-padding` を指定するのもありらしい

2024-04-13 08:25 UTC, sor4chi commented on src/app/page.tsx
>                </div>
ヘッダーがー全ページ共通なのでbodyで良さそう

2024-04-13 09:57 UTC, batora9 commented on src/app/page.tsx
>                </div>
```css
.body {
    scroll-margin-top: 72px;
}
```
を追加しましたが変わりません。何が間違ってますか？

2024-04-13 11:07 UTC, sor4chi commented on src/app/page.tsx
>                </div>
bodyはクラスではなくタグなので

```css
body {
```

っすね

2024-04-13 11:10 UTC, batora9 commented on src/app/page.tsx
>                </div>
それだと
`Syntax error: Selector "body" is not pure (pure selectors must contain at least one local class or id)`
っすね

2024-04-13 11:20 UTC, sor4chi commented on src/app/page.tsx
>                </div>
global.cssに書きました？

2024-04-13 11:22 UTC, batora9 commented on src/app/page.tsx
>                </div>
global.cssにも書きましたが変わらないです

2024-04-13 11:46 UTC, sor4chi commented on src/app/page.tsx
>                </div>
嘘ダァ

2024-04-13 11:51 UTC, sor4chi commented on src/app/page.tsx
>                </div>
![Screenshot 2024-04-13 at 20 51 22](https://github.com/saitamau-maximum/public-website/assets/80559385/5368bcba-1ffe-456d-a527-f066e81b3afe)

これでいけたわ

2024-04-13 14:11 UTC, a01sa01to commented
@batora9 なおした？ push されてる？

2024-04-14 01:18 UTC, batora9 commented
しました！お願いします

2024-04-14 01:25 UTC, a01sa01to commented on src/app/global.css
> +  scroll-padding-top: 80px !important;
`!important` いる？ specificity が壊れるのでなるべく避けたい

2024-04-14 01:52 UTC, batora9 commented on src/app/global.css
> +  scroll-padding-top: 80px !important;
なしでもいけました

2024-04-14 02:44 UTC, a01sa01to commented on src/app/about/styles.module.css
>  }
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/f976f5e1-5ddb-4bad-b5d8-8c856c9866f2)

レイアウト崩れてそう (ここでやるべきじゃないかもしれないけど一応見つけたので)
`box-sizing: border-box` を追加すればなおります

2024-04-14 02:54 UTC, batora9 commented on src/app/about/styles.module.css
>  }
ここでやるものじゃないと思ってスルーしてました
一応直しました

2024-04-14 03:01 UTC, a01sa01to commented on src/app/about/styles.module.css
> +    box-sizing: border-box
```suggestion
    box-sizing: border-box;
```

2024-04-14 03:01 UTC, a01sa01to commented on src/app/about/styles.module.css
>  }
なるほど、ありがとう～

2024-04-14 03:04 UTC, batora9 commented on src/app/about/styles.module.css
> +    box-sizing: border-box
焦ってました

2024-04-14 03:21 UTC, a01sa01to approved these changes

2024-04-14 07:34 UTC, sor4chi approved these changes

2024-04-14 07:34 UTC, merged