Feat/Newページ仕上げ
saitamau-maximum/public-website pull request #84
Opened 2024-04-13 04:24 UTC by nakamuraitsuki

useStateとマークダウン関係のものが共存できなかったので切り分けました。

2024-04-13 08:57 UTC, batora9 commented
レスポンシブ対応おれがやるね

2024-04-13 11:09 UTC, sor4chi commented on src/app/news/[slug]/page.tsx
> +            <article dangerouslySetInnerHTML={{ __html: html.content }} />
Articleコンポーネント使った方がいいかも

2024-04-13 11:09 UTC, sor4chi commented on src/components/news-page-list/news-list-view.tsx
> +  */}
いらないコードは消しちゃおう

2024-04-13 11:09 UTC, sor4chi commented on src/components/news-page-list/news-page-list.tsx
> +export async function NewsPageList(this: any) {
このthis:anyってなんだ

2024-04-13 11:10 UTC, sor4chi requested changes
お願いします

2024-04-13 14:21 UTC, a01sa01to requested changes

2024-04-13 14:21 UTC, a01sa01to commented on src/app/news/[slug]/page.tsx
> +              { title: '新着情報', href: '/news' },
そういえばこっちは「新着情報」になってるけど `/news` は「ニュース一覧」、タイトルは「News」になってるのでどれかに統一したほうがいいかも？

2024-04-13 14:21 UTC, a01sa01to commented on src/components/news-page-list/news-page-list.module.scss
> +.noNeed {
クラス名変えたほうがいいかも (noNeed ってなんでだ)

2024-04-13 14:21 UTC, a01sa01to commented on src/components/news-page-list/news-page-list.module.scss
> +}
![image](https://github.com/saitamau-maximum/public-website/assets/26807394/66b33e6d-03cd-433e-bf4b-7f9348ff3e45)

実は中央揃えになっていないので `padding-left: 0` を追加してもらえると :pray: (`ul` のデフォルト padding がついてるせいです)

2024-04-14 03:26 UTC, batora9 requested changes

2024-04-14 03:26 UTC, batora9 commented on src/app/news/page.tsx
>            </div>
`/news`ページのパンくずリスト書き換え忘れてた...以下のように修正しておいて！
```tsx
          <div className={style.breadcrumb}>
            <Link href='/' className={style.breadcrumbLink}>
              Top
            </Link>
            <p className={style.breadcrumbLink}>&nbsp;&gt;&nbsp;</p>
            <Link href='/news' className={style.breadcrumbLink}>
              News
            </Link>
          </div>
```
↓
```tsx
          <Breadcrumb
            items={[
              { title: 'Top', href: '/' },
              { title: '新着情報', href: '/news' },
            ]}
          />
```

2024-04-14 03:30 UTC, a01sa01to requested changes

2024-04-14 03:30 UTC, a01sa01to commented on src/components/news-page-list/news-list-view.tsx
> +        nextLinkClassName={style.noNeed} //'>'のリンクのクラス名
noNeed が css 側になさそう

2024-04-14 03:30 UTC, a01sa01to commented on src/components/news-page-list/news-page-list.module.scss
>  }
どうせ見せないなら `display: none` でいいんじゃないかと思ったけど崩れる？

2024-04-14 03:30 UTC, a01sa01to commented on src/app/news/[slug]/page.tsx
> +              { title: 'news', href: '/news' },
https://github.com/saitamau-maximum/public-website/pull/84#discussion_r1564059031

これ、Breadcrumb と HeroImage のほうも統一したほうがいいのではという意図でした :bow:
あとでやるならそれでもいいかもです

2024-04-14 03:32 UTC, batora9 commented on src/app/news/[slug]/page.tsx
> +              { title: 'news', href: '/news' },
@nakamuraitsuki 命名は任せます

2024-04-14 03:59 UTC, nakamuraitsuki commented on src/components/news-page-list/news-page-list.module.scss
>  }
崩れなかったので、そのように修正します。ありがとうございます。

2024-04-14 19:47 UTC, sor4chi commented
開発が止まっているっぽいので自分がキャッチアップします、ごめんね @nakamuraitsuki 途中までありがとう！

2024-04-14 20:44 UTC, batora9 requested changes

2024-04-14 20:44 UTC, batora9 commented on src/app/news/[slug]/page.tsx
> +              { title: data.title, href: `/news/${slug}` },
ここらへんのパンくずとheroのテキストがバラバラなの直してほしいです！

2024-04-14 20:46 UTC, sor4chi commented on src/app/news/[slug]/page.tsx
> +              { title: data.title, href: `/news/${slug}` },
なんと！そこもあったのか

2024-04-14 23:25 UTC, a01sa01to reviewed
これ終わったらテスト記事は消す？

2024-04-15 00:40 UTC, sor4chi commented
> これ終わったらテスト記事は消す？

@batora9

2024-04-15 01:04 UTC, batora9 commented
@sor4chi `test[2-9].md`を消しちゃってください！おねがいします

2024-04-15 01:09 UTC, a01sa01to approved these changes

2024-04-15 01:10 UTC, batora9 approved these changes

2024-04-15 01:14 UTC, batora9 commented
そらちさんがapproveしないとmergeできなそう？
mergeまでしちゃってください！

2024-04-15 01:17 UTC, yukikamome316 commented
> そらちさんがapproveしないとmergeできなそう？ mergeまでしちゃってください！

@batora9 俺でもいいなら今できる

2024-04-15 01:19 UTC, sor4chi approved these changes

2024-04-15 01:20 UTC, merged