feat: 入会案内ページを作成
saitamau-maximum/public-website pull request #85
Opened 2024-04-13 09:49 UTC by batora9

Figmaとのデザインで異なる部分がありますが、@hana-rsと話し合って決めました。

2024-04-13 11:11 UTC, sor4chi commented
これってサークル講習会開催日に対面で参加することが必須なの？

2024-04-13 11:32 UTC, batora9 commented
@sor4chi 変更しました

2024-04-13 11:45 UTC, sor4chi requested changes
だんだんコード読みやすくなってきたね
良さそう

2024-04-13 11:45 UTC, sor4chi approved these changes
良さそうとか言いながらRCしちゃったw

2024-04-13 14:10 UTC, a01sa01to commented on src/app/join/page.tsx
> +              サークルの講習会開催日に
講習会開催日ってガイダンスと勘違いしそうだなーと思うなど
普通にサークルの活動日とかでよさそう？

2024-04-13 21:17 UTC, batora9 commented
@a01sa01to 修正しました～

2024-04-14 00:59 UTC, a01sa01to approved these changes

2024-04-14 01:04 UTC, merged