FAQのデザイン
saitamau-maximum/public-website pull request #86
Opened 2024-04-13 17:37 UTC by shigekk

2024-04-13 21:27 UTC, batora9 requested changes

2024-04-13 21:27 UTC, batora9 commented on src/app/faq/page.tsx
> +        </div>
この部分繰り返し使ってるからコンポーネントにしてもいいと思う

2024-04-14 01:33 UTC, a01sa01to requested changes

2024-04-14 01:33 UTC, a01sa01to commented on src/app/faq/page.module.scss
> +}
Next.js (というか autoprefixer) によって自動で `-webkit-box-shadow`, `-moz-box-shadow` は付加されるので `box-shadow` だけで OK (のはず) です
box-shadow を共通化したいという感じであれば variables とかにまとめちゃうのがいいかも (どうせほかでも使うので)

2024-04-14 01:33 UTC, a01sa01to commented on src/app/faq/page.module.scss
> +  }
この文字は `Q` 固定 なので`::before` 疑似要素を使ってもいいかもしれない (`A` も同様)

```suggestion
  &::before {
    content: 'Q';
    font-size: 2rem;
    color: #439154;
    margin: 0 1rem 0 0;
  }
```
(間違ってるかも)

2024-04-14 01:33 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            プログラミング初心者なんですが、大丈夫ですか？{' '}
```suggestion
            プログラミング初心者なんですが、大丈夫ですか？
```

末尾の空白消そう (ほかの部分も)

2024-04-14 07:31 UTC, shigekk commented
帰ったらコンポーネント作ります

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            <div className={styles.chara}>A</div>{' '}
```suggestion
            <div className={styles.chara}>A</div>
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            活動内容を教えてください！{' '}
```suggestion
            活動内容を教えてください！
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            会費はいくらかかるのでしょうか？{' '}
```suggestion
            会費はいくらかかるのでしょうか？
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            情報工学科じゃないけれど入れる？{' '}
```suggestion
            情報工学科じゃないけれど入れる？
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            どうやって練習をしているの？{' '}
```suggestion
            どうやって練習をしているの？
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            <div className={styles.chara}>Q</div>使う言語は？{' '}
```suggestion
            <div className={styles.chara}>Q</div>使う言語は？
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            <div className={styles.chara}>A</div>{' '}
```suggestion
            <div className={styles.chara}>A</div>
```

2024-04-14 07:34 UTC, a01sa01to commented on src/app/faq/page.tsx
> +            <div className={styles.chara}>Q</div>人数はどのくらい？{' '}
```suggestion
            <div className={styles.chara}>Q</div>人数はどのくらい？
```

2024-04-14 19:55 UTC, batora9 commented
@shigekk ガイダンスに合わせて公開する予定なので修正しちゃいます
途中までありがとう！

2024-04-14 21:23 UTC, batora9 approved these changes
完璧。自己満

2024-04-14 23:24 UTC, a01sa01to commented on src/app/faq/page.tsx
> +          question='FAQに載ってないことはどこで聞けますか?'
nits
```suggestion
          question='FAQに載ってないことはどこで聞けますか？'
```

2024-04-15 00:34 UTC, shigekk commented
> @shigekk ガイダンスに合わせて公開する予定なので修正しちゃいます
> 途中までありがとう！

すまん！ありがとうございます

2024-04-15 00:44 UTC, sor4chi approved these changes

2024-04-15 01:08 UTC, a01sa01to approved these changes

2024-04-15 01:11 UTC, merged