docs: サイトリニューアルのニュースを追加
saitamau-maximum/public-website pull request #92
Opened 2024-04-14 18:15 UTC by yukikamome316

2024-04-14 19:03 UTC, sor4chi commented
@yukikamome316 これ見た目はまた別でやるってことでおk？

2024-04-14 19:05 UTC, batora9 commented
@sor4chi https://github.com/saitamau-maximum/public-website/pull/84 これです

2024-04-14 19:05 UTC, batora9 approved these changes

2024-04-14 19:05 UTC, yukikamome316 commented
> @yukikamome316 これ見た目はまた別でやるってことでおk？

@sor4chi 
そうです
#84 で対応中です

2024-04-14 19:06 UTC, sor4chi commented
@yukikamome316 @batora9 
あーだからドキュメントなのね！了解
今度からPRの本文に書いてくれるととても助かる

2024-04-14 23:20 UTC, a01sa01to commented on docs/news/website-migration.md
> +title: 'サイト移行のお知らせ'
「リニューアル」が良さそう？
移行だと (個人的には) ドメインも変えたイメージになるので

2024-04-15 00:39 UTC, sor4chi approved these changes
Asaさんの直したらOK

2024-04-15 02:19 UTC, a01sa01to approved these changes

2024-04-15 02:19 UTC, a01sa01to commented
conflict なおしてね

2024-04-15 02:29 UTC, a01sa01to approved these changes

2024-04-15 02:30 UTC, a01sa01to requested changes
テストが復活してる

2024-04-15 02:35 UTC, a01sa01to approved these changes

2024-04-15 02:35 UTC, merged